### ISSUE TITLE
Formatting of table needed

### ISSUE THREAD

**Issue by dizzzz** [eXistSolutions/hsg-shell#101]
`http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/production-and-timeliness-data` does not look nice : 

original:

![original_table](https://cloud.githubusercontent.com/assets/1700062/12376641/3bd46352-bcff-11e5-851d-cfba5ffe7625.gif)

new:

![new_table](https://cloud.githubusercontent.com/assets/1700062/12376643/46007b68-bcff-11e5-86b5-833e4effae23.gif)

**Comment by plutonik-a** [comment]
Fixed with: https://github.com/eXistSolutions/hsg-shell/commit/6b6b67e7e99c2f65e26abdc198e8140a496c998a and https://github.com/eXistSolutions/hsg-shell/commit/7a9169bac81f3f9b14a6db8f077504c3b9c8013c

**Comment by plutonik-a** [comment]
Needs to be rolled back and fixed with #118
