### ISSUE TITLE
Handle absolute links

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#103]
http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/style

The link to Thomas Jefferson is an absolute path incorrectly leading to http://localhost:8080/milestones/1776-1783/b-franklin

![image](https://cloud.githubusercontent.com/assets/607433/12453407/608ece4e-bf93-11e5-95c0-42b541e85f1f.png)

**Comment by joewiz** [comment]
Confirmed. Thanks @wolfgangmm!
