### ISSUE TITLE
Twitter messages run out of sidebar

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/hsg-shell#104]
see attached image
![homepage](https://cloud.githubusercontent.com/assets/484059/12642448/19bffadc-c5b6-11e5-8481-03e624cf298c.png)

**Comment by line-o** [comment]
The links (and links to hastags) are separated with non-breaking spaces.

**Comment by line-o** [comment]
The social media sidebar now looks like this:
<img width="377" alt="screen shot 2016-02-19 at 13 20 35" src="https://cloud.githubusercontent.com/assets/657222/13175662/47d41338-d70c-11e5-998f-f1f6e0396d26.png">
Tested with fake tweets with really long hashtags.
