### ISSUE TITLE
URL for people's portrait images is wrong

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#105]
Maybe the path is wrongly put together.
For example, the URL should be 
//s3.amazonaws.com/static.history.state.gov/secretaries/jefferson-thomas.jpg
instead of 
//s3.amazonaws.com/static.history.state.gov/jefferson-thomas/jefferson-thomas.jpg

All subpages in 
[http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/secretaries](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/secretaries) are affected.
[https://history.state.gov/beta/departmenthistory/people](https://history.state.gov/beta/departmenthistory/people)

**For example:**
<img width="852" alt="wrong-image-url" src="https://cloud.githubusercontent.com/assets/1157669/13151899/93ad49d2-d66c-11e5-8ed4-46d92f071c74.png">

**Should be like this:**
<img width="815" alt="fixed in browser" src="https://cloud.githubusercontent.com/assets/1157669/13151928/affbedb4-d66c-11e5-9239-86714e5bfb3c.png">

This is a follow-up issue from https://github.com/eXistSolutions/hsg-shell/issues/82

**Comment by wolfgangmm** [comment]
Image paths should be correct by now:

![image](https://cloud.githubusercontent.com/assets/607433/13877891/e932bbfa-ed0d-11e5-81f6-5ed95669b26f.png)
