### ISSUE TITLE
Mobile: Headings are too large

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#111]
On mobile devices the font-sizes are too large and sometimes filling the whole screen. 
We need to add some breakpoints with smaller font-sizes.

<img width="300" alt="bug-06-fonts-too-large" src="https://cloud.githubusercontent.com/assets/1157669/13187708/0da1f23e-d74d-11e5-9d29-7a10d1cb6248.png">

**Comment by joewiz** [comment]
@plutonik-a Agreed.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/c20c882b98d45393bef7a5cc2f168486c61d1cdc

**Comment by plutonik-a** [comment]
<img width="320" alt="bildschirmfoto 2016-03-30 um 17 12 18" src="https://cloud.githubusercontent.com/assets/1157669/14147248/ea552d2e-f69a-11e5-9630-78422610745b.png">
