### ISSUE TITLE
Left content margin is missing on smaller screens 

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#114]
On breakpoint screen width 991px, the content sticks on the left side with nearly no margin.
Also there are different alignments regarding small heading, breadcrumb, content and menu.

[http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775/foreword](http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775/foreword)

<img width="866" alt="bug-17-wrong-grid-mobile" src="https://cloud.githubusercontent.com/assets/1157669/13188681/2c33b0c4-d753-11e5-8925-3814d4e2f2e4.png">

**Comment by line-o** [comment]
#88 is related because the arrows are actually part of the page and therefore affect its flow. The red headline is pushed so far to the left because of this.
