### ISSUE TITLE
Create TEI-table classes in ODD

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#118]
TEI tables need to be styled independently from surrounding webpage context.
As reported in issue #101, styling for bordered tables is missing.
General use of bootstrap classes resulted in conflicts, so we need the table styles within ODD.

We can define a default style for tables, unless `@rendition` is given.

Related:
https://github.com/eXistSolutions/hsg-shell/issues/72#issuecomment-167119871
https://github.com/eXistSolutions/hsg-shell/commit/7a9169bac81f3f9b14a6db8f077504c3b9c8013c
https://github.com/eXistSolutions/hsg-shell/issues/90
https://github.com/wolfgangmm/tei-simple-pm/commit/f305bc294da7cc75fe5a8833985bede23ecbb3c8

**Comment by wolfgangmm** [comment]
Table with local renditions now looks like this:

![image](https://cloud.githubusercontent.com/assets/607433/13423093/313d770a-df99-11e5-9e4b-3d19a4c798f3.png)

And without rendition:

![image](https://cloud.githubusercontent.com/assets/607433/13423111/48e8fcf8-df99-11e5-90a2-0b0e6c78617d.png)

Still some cell spacing may need to be added for both types of tables.

**Comment by plutonik-a** [comment]
I found a table on [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/documents/1984-07-slany-report-to-congress](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/documents/1984-07-slany-report-to-congress), which shouldn't be bordered [history.state.gov/historicaldocuments/frus-history/documents/1984-07-slany-report-to-congress](https://history.state.gov/historicaldocuments/frus-history/documents/1984-07-slany-report-to-congress).

Looking into the content xml `/db/apps/frus-history/documents/1984-07-slany-report-to-congress.xml`, I couldn't find any hint of keeping rendition. 

Is this on purpose or is it a mistake?

**Comment by wolfgangmm** [comment]
Using table-bordered on any table which does not have a local rendition should be ok.
