### ISSUE TITLE
Position of search field on Tablet view

### ISSUE THREAD

**Issue by line-o** [eXistSolutions/hsg-shell#119]
<img width="503" alt="screen shot 2016-02-23 at 20 54 21" src="https://cloud.githubusercontent.com/assets/657222/13264730/d9fc2eb0-da6f-11e5-9955-a226cacb747e.png">

The search field should always stay in roughly the same position until it switches into the top navigation bar.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/4a52b2107b1828d136c9bb6ac26f9614b5701c14
