### ISSUE TITLE
Historical Documents overview on smaller screens

### ISSUE THREAD

**Issue by line-o** [eXistSolutions/hsg-shell#120]
In contrast to the large desktop view the links to each administration is shown in a long vertical row.

<img width="831" alt="screen shot 2016-02-19 at 22 43 26" src="https://cloud.githubusercontent.com/assets/657222/13264790/1e89b98a-da70-11e5-838b-f498041beecd.png">

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/156/commits/c19492cdb846ad955a698296839e44c8741e10ce and https://github.com/eXistSolutions/hsg-shell/pull/156/commits/f1feaa9d7dbfc7c722dc57b8a701e8e36b517d08
