### ISSUE TITLE
Placement of arrows for TEI document view

### ISSUE THREAD

**Issue by line-o** [eXistSolutions/hsg-shell#121]
The arrows to jump to the next or previous document, on historicaldocuments for example, separates it from the neighboring boxes with related information.

<img width="320" alt="screen shot 2016-02-22 at 14 44 50" src="https://cloud.githubusercontent.com/assets/657222/13265334/ae10f65c-da72-11e5-99e7-123d447d227e.png">

I propose to tie these both items closer together to maintain their relation visually.

<img width="320" alt="screen shot 2016-02-22 at 14 45 09" src="https://cloud.githubusercontent.com/assets/657222/13265341/b8bca060-da72-11e5-99b1-cda77cd235f6.png">

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/156/commits/f447d64bf3e3265814e615a72e39dc158ed62c5e and https://github.com/eXistSolutions/hsg-shell/pull/156/commits/bb921346090f09618231c443a8b6cee7122330df
