### ISSUE TITLE
List spacing

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#123]
In some cases lists in the main content seem to have bad spacing:

http://192.168.2.107:8000/exist/apps/hsg-shell/historicaldocuments/frus1952-54v02p1/d5

![image](https://cloud.githubusercontent.com/assets/607433/13399104/f313220a-df01-11e5-973c-ac5971855a94.png)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/137
Waits for review & merge.

New output:
<img width="787" alt="bildschirmfoto 2016-03-04 um 20 18 23" src="https://cloud.githubusercontent.com/assets/1157669/13537698/6b883c4c-e246-11e5-996d-bf8e60e99c9d.png">
