### ISSUE TITLE
Sidebar navigation in non-FRUS sections not working

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#13]
In the short-history and buildings sections:

  http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history
  http://localhost:8080/exist/apps/hsg-shell/departmenthistory/buildings

... clicking on the left sidebar toc navigation has no effect.  Well, the URL bar updates, but the content doesn't change.  I don't see any indication of failed network requests in Chrome's Developer Tools.  So I'm not sure how to dig deeper.

Force-reloading the page successfully loads the requested page.  So it seems to me the ajax is somehow capturing the link and not doing anything with it.

**Comment by joewiz** [comment]
@tuurma Thanks! But after updating to the new version with your commits I'm still seeing the problem. Could you please confirm that clicking on the left sidebar table of contents navigation links from pages like http://localhost:8080/exist/apps/hsg-shell/about/hac, you are actually seeing the requested content and not just seeing the URL bar change its value?

(I'm currently seeing 404s on Buildings, Short History, or FAQ, which I suspect I might've introduced after my recent work on the controller.xql file, so I'm not able to test the sidebar TOC behavior on those pages, but I suspect fixing it on the HAC pages will fix the problem on these other pages too.)

**Comment by tuurma** [comment]
Oupps, yes, I think I got sidetracked into another issue here and ignored your initial point. So yes, unfortunately the behaviour is still as you describe, and I will look into that again.

**Comment by joewiz** [comment]
@tuurma Thanks! As I'm reading the diff, I see two primary changes: (1) you extended frus-ajax.xqm to work for non-FRUS sections and (2) you added `<div id="content-container">` inside the existing `<div id="content-inner">` for all of the HTML files in pages. How did (2) contribute to this fix?

**Comment by tuurma** [comment]
Ajax calls needs a container to target the  place in which replace the content, so `<div id="content-container">` basically provides such
