### ISSUE TITLE
Document list breaks after link

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#131]
Current view of http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v26 - notice that "Documents 1-60" appears on the line following the chapter title:

> ![screen shot 2016-03-04 at 3 10 18 am](https://cloud.githubusercontent.com/assets/59118/13521466/bf6bb20c-e1b6-11e5-8a8f-6c095a6ff15a.png)

Contrast this with the view of the same page on hsg, https://history.state.gov/historicaldocuments/frus1977-80v26: 

> ![screen shot 2016-03-04 at 3 12 33 am](https://cloud.githubusercontent.com/assets/59118/13521492/fb9d0f14-e1b6-11e5-8cd7-00b3bc13f521.png)

By disabling `display:block` on `.toc-inner a` in `_toc.scss`, this issue goes away, although the change seems to have an effect on spacing elsewhere in the list:

> ![screen shot 2016-03-04 at 3 10 27 am](https://cloud.githubusercontent.com/assets/59118/13521516/2a9d2b00-e1b7-11e5-880f-c301e1de4ecb.png)

Your help in preventing the line break in image 1 above while retaining balanced spacing lost in image 3 would be most helpful.

**Comment by plutonik-a** [comment]
For a screenshot you can have a look here: https://github.com/eXistSolutions/hsg-shell/issues/132#issuecomment-192357942
