### ISSUE TITLE
[TOC] Nesting of list elements is wrong: A list item is duplicated and messes-up levels

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#133]
Current status:
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v09](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v09)

Desired: 
[https://history.state.gov/historicaldocuments/frus1945v09](https://history.state.gov/historicaldocuments/frus1945v09)

<img width="878" alt="historicaldocuments-frus1945v09" src="https://cloud.githubusercontent.com/assets/1157669/13534129/eb5cbe1a-e233-11e5-8b61-d0362b564c04.png">

**Comment by wolfgangmm** [comment]
I tracked this down to a bug in eXist: https://github.com/eXist-db/exist/pull/947

Should be fixed once pull request is accepted.
