### ISSUE TITLE
do we need to cache expensive pages?

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#14]
Pages like back of book indexes (e.g., http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v18/index) are expensive to be generated.  I suspect load tests would show the site is quickly overwhelmed by, say, 100 requests to the same page.  Please create a load test to verify this, and, if this is true, propose an approach to caching.

**Comment by tuurma** [comment]
Did a preliminary index conf for such pages, it already improves situation, but I cannot push to frus, so here it goes:

<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <fulltext default="none" attributes="false"/>
        <range>
        <create qname="@id" type="xs:string"/>
        </range>
    </index>
</collection>

**Comment by tuurma** [comment]
Looks like this single index already improves the performance of index pages by 10 times approx, also fixes a lot of other slowly loading pages.

**Comment by joewiz** [comment]
@tuurma Thanks for pointing out the lack of proper index configuration files. I've just committed a set for the frus project: https://github.com/HistoryAtState/frus/commit/7413c96455aaa87157f5bc7622ea3019efd48208.

The background about this request is that on the current version of history.state.gov, concurrency and locking issues led us to cache expensive pages. Hopefully the new design will lighten this load considerably, but as we perform load testing, we should be attuned to pages that still take time to generate and would thus benefit from offloading through some caching system.

**Comment by joewiz** [comment]
closing this pending completion of load tests
