### ISSUE TITLE
Tooltips and popovers appear in Helvetica

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#140]
I noticed that the fonts used in tooltips and popovers - such as in FRUS sidebars and footnotes - is still Helvetica, even though we've moved to a new sans-serif font. See:

> ![screen shot 2016-03-08 at 10 21 53 am](https://cloud.githubusercontent.com/assets/59118/13605875/a81d7464-e517-11e5-9006-18ef9218a8cf.png)

Would it make sense to standardize on the new sans-serif font?

I think the source of these font settings are the style.css file:

- https://github.com/eXistSolutions/hsg-shell/blob/master/resources/css/style.css#L5962
- https://github.com/eXistSolutions/hsg-shell/blob/master/resources/css/style.css#L6076

I also noticed a few other `font-family` definitions here, including one on `body`, which I'm guessing should be removed or superseded by the newer, consolidated CSS framework.

**Comment by plutonik-a** [comment]
@joewiz Could you please provide an exact link each for a tooltip/footnote and a popover/sidebar?

The fonts you mentioned are set by bootstrap, I simply have to override them, no big deal:
The output css (your links above) is a generated stylesheet from its sourcefile [main.scss](https://github.com/eXistSolutions/hsg-shell/blob/master/app/scss/main.scss).
It contains imported bootstrap styles and our imported individual styles. 
The ordering of imports determines which style is finally rendered by the browser.

> Would it make sense to standardize on the new sans-serif font?

Yes, definitely. This is the plan I'm working on, according to this styleguide:
[https://playbook.cio.gov/designstandards/visual-style/](https://playbook.cio.gov/designstandards/visual-style/), see chapter about "Source Sans Pro headings, Merriweather body".

> I also noticed a few other font-family definitions here, including one on body, which I'm guessing should be removed or superseded by the newer, consolidated CSS framework.

Where did you notice other font-families than Merriweather or Sans-Pro apart from classes tooltip and popover, which are actually applied to elements on the site?

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/045ee4725d46ce3be3f4f19bc18f50da8de9947b

Related: https://github.com/eXistSolutions/hsg-shell/commit/4fb4981191806466a9eacad136f165f9ab465dcf

@joewiz Please let me know, if I understood you right with this fix (I also changed the markup for the aside element). The heading of the `<aside>` is `font-family: Sans Pro`, the tooltip as well because of better legibility and the popover has the Merriweather serif font.

You can check 
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v01p1/d96](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v01p1/d96) or
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v02p1/d5](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v02p1/d5)

**Comment by joewiz** [comment]
@plutonik-a Thank you, and apologies for not getting back to you with the URLs you requested. I'm away from my development machine, so while the code changes I see here look like they do the right thing, could you please (as is our practice) post a screenshot demonstrating the new appearance when you have the chance?

**Comment by plutonik-a** [comment]
No problem, I will post a screenshot and summary in every layout-issue from now on.

**Side Panel and Tooltips:**
* panel was a `<div>`, now `<aside>`. 
* had no headline, now `<h4>` as heading
* panel heading has font-family `Sans Pro` as all headings on page
* panel list elements have `Merriweather Serif` like default body font-family
* tooltip has font-family `Sans Pro` for better legibility

<img width="253" alt="tooltips" src="https://cloud.githubusercontent.com/assets/1157669/13666655/eb2e8b48-e6b2-11e5-99a3-5a699319b026.png">

**Popovers:**
* was font-size ~11px, now 13px and 1.7em line-height for better legibility

<img width="794" alt="popover" src="https://cloud.githubusercontent.com/assets/1157669/13666671/fe98c630-e6b2-11e5-8484-3012d903e030.png">

**Side Navigation:**
<img width="546" alt="side-navigation" src="https://cloud.githubusercontent.com/assets/1157669/13666683/0de57ef8-e6b3-11e5-8120-220e417ca31e.png">

**Comment by joewiz** [comment]
This summary is very helpful, and the changes look great. Many thanks!
