### ISSUE TITLE
XQuery error on frus-history/appendix-a

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#142]
http://localhost:8000/exist/apps/hsg-shell/historicaldocuments/frus-history/appendix-a

![image](https://cloud.githubusercontent.com/assets/607433/13610010/e0dc3058-e55b-11e5-83a1-2f0227b9dbb3.png)

**Comment by line-o** [comment]
There is no such call to `console:log` in the current version of `pages:load` on master branch.

**Comment by wolfgangmm** [comment]
Ok, my mistake. It was a local addition. Sorry for the noise.
