### ISSUE TITLE
Unify sidebar widths

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#145]
https://github.com/eXistSolutions/hsg-shell/commit/4fb4981191806466a9eacad136f165f9ab465dcf#diff-74c0455e76ac55e74edb3ecfdeff916aR55 is a good illustration of the varying widths we currently have on sidebars.  I think all should be `<aside class="col-md-3">`, and most already are, but the following pages have different values:

- pages/about/hac/section.html: `<aside class="col-md-2">`
- pages/historicaldocuments/index.html: `<aside class="col-md-2">`
- pages/historicaldocuments/volume-interior.html: `<aside class="col-lg-2 col-md-2 col-sm-2 hidden-xs" data-template="frus:facets">`
- pages/historicaldocuments/volume-landing.html: `<aside class="col-md-offset-1 col-md-2">`

I think these can all safely be changed to `col-md-3`.

**Comment by plutonik-a** [comment]
Related issue: #116

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/156
