### ISSUE TITLE
[Search-volumes] Volumes are not displayed

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#147]
On the [search page for volume titles](http://localhost:8080/exist/apps/hsg-shell/search/select-volumes), there is only the variable for volume titles printed out as a string ...

<img width="302" alt="select-volumes" src="https://cloud.githubusercontent.com/assets/1157669/13707807/b5fe4b1c-e7ab-11e5-99ba-7195056c7488.png">

... instead of a list, which should actually look like this:
[https://history.state.gov/search/select-volumes](https://history.state.gov/search/select-volumes)

Here is the code where I found the variables with no further function:
[https://github.com/eXistSolutions/hsg-shell/blob/master/pages/search/select-volumes.html#L30-L31](https://github.com/eXistSolutions/hsg-shell/blob/master/pages/search/select-volumes.html#L30-L31)

In the `pages/search/index.html` template however, I found some code about volume search, that isn't rendered for some reason, but I added the classes for checkboxes anyway:
[https://github.com/eXistSolutions/hsg-shell/blob/master/pages/search/index.html#L56-L82](https://github.com/eXistSolutions/hsg-shell/blob/master/pages/search/index.html#L56-L82)

**Comment by plutonik-a** [comment]
Related https://github.com/eXistSolutions/hsg-shell/issues/95

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/2649b8b1e821b17f3163730650b1ba08b272bad7

**Comment by joewiz** [comment]
Looks great, thank you!
