### ISSUE TITLE
people pages "not found"

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#148]
I'm getting 404 errors on all people pages. For example:

- http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/eacho-william-carlton
- https://history.state.gov/beta/departmenthistory/people/eacho-william-carlton

These are linked from Department History > Principal Officers and Chiefs of Mission.

**Comment by joewiz** [comment]
Some observations about this issue:

The error goes away if we remove the `@data-template="pages:load"` from https://github.com/eXistSolutions/hsg-shell/blob/master/pages/departmenthistory/people/person.html#L3.  

But this isn't a fix, because then any people entries who are "secretary of state" no longer show the biographical article we have about that secretary, e.g., https://history.state.gov/departmenthistory/people/jefferson-thomas - namely, the problem that #82 fixed.

The key thing to know about this page is that it shows different content depending on whether the requested person was a "secretary of state" or not:

- case 1: is not a secretary: show only listing of person's dates of service, e.g. https://history.state.gov/departmenthistory/people/eacho-william-carlton

- case 2: is a secretary: show both biographical article and listing of dates of service, e.g., https://history.state.gov/departmenthistory/people/jefferson-thomas

Before #82, we had case 1 working, but case 2 wasn't working. After #82, case 2 worked, but case 1 broke.  The solution has to account for both cases.

**Comment by wolfgangmm** [comment]
Not a secretary of state:

![image](https://cloud.githubusercontent.com/assets/607433/13819182/e7e7f074-eb98-11e5-8c86-7f878c71ab3b.png)

Secretary:

![image](https://cloud.githubusercontent.com/assets/607433/13819211/06423a52-eb99-11e5-8ff2-4b0ecf92c428.png)

Some additional styling might be needed for the right sidebar.
