### ISSUE TITLE
<title> must be page specific

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#15]
Page `<title>` elements must be customizable. These currently all appear as:

    <title data-template="config:app-title">history.state.gov 3.0 shell</title>

We need to be able to customize these on a per-page basis.

**Comment by joewiz** [comment]
(Note: I just fixed the markdown in the original issue description above. The display was kind of mangled. Sorry I didn't catch this before, if it caused any confusion!)

**Comment by joewiz** [comment]
Thanks, @tuurma and @wolfgangmm.  Could you point me to which pages the solution here is fully implemented on?  That way I will know which pages it has yet to be applied to.

**Comment by tuurma** [comment]
Hi @joewiz, so far it has been applied to volumes in /historicaldocuments

Pages that are missing this completely:
/historicaldocuments itselft
/historicaldocuments/status-of-the-series
/historicaldocuments/frus-history
/historicaldocuments/ebooks

And others that have the generated title, but it's not what it should be, typically missing publication titles etc:
/departmenthistory
/milestones
/countries
/about

**Comment by joewiz** [comment]
Great, thanks for this info, @tuurma.
