### ISSUE TITLE
Incorrect Titles

### ISSUE THREAD

**Issue by line-o** [eXistSolutions/hsg-shell#151]
- [ ] **historicaldocuments/frus1952-54v02p1/d5**
Test link: http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v02p1/d5 
The title gets some paragraph text and is too long

- [ ] **FAQ**
Title should match breadcrumb hierarchy (starting with "Frequently Asked Questions") but is "Documents on the History of U.S. Foreign Relations - FAQ - About Us - Office of the Historian"
Test link: http://localhost:8080/exist/apps/hsg-shell/about/faq

- [ ] **Frus History Overview**
Title should be "History of the FRUS document"
Test link: http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history

- [ ] **Frus History Document Pages**
Titles should be in the form "Document 1", etc. instead of using the document's div/head. see . follow the pattern for breadcrumbs.
Test link: http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v03/d1

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/issues/187
