### ISSUE TITLE
Volumes not yet published should show publication status

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#154]
Volumes that are not yet published need to show the publication status of the volume. For example, on the current site:

- https://history.state.gov/historicaldocuments/frus1977-80v24

> ![screen shot 2016-03-16 at 5 31 02 pm](https://cloud.githubusercontent.com/assets/59118/13829349/eda78a66-eb9c-11e5-8625-fa0933194079.png)

Compare to hsg-shell:

- http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v24
or 
- https://history.state.gov/beta/historicaldocuments/frus1977-80v24

> ![screen shot 2016-03-16 at 5 34 00 pm](https://cloud.githubusercontent.com/assets/59118/13829424/50d43c60-eb9d-11e5-9a1b-f0ed5ab22148.png)

**Comment by joewiz** [comment]
For code probing the publication status of volumes, see the "Status of the Series" page:

- http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/status-of-the-series

See functions in `modules/frus-html.xqm` like `fh:volumes-planned-for-publication-this-year()`. They probe FRUS metadata with this kind of query:

```xquery
collection($config:FRUS_METADATA_COL)/volume[publication-status ne 'published']
```

**Comment by joewiz** [comment]
A corollary is that volumes that have been published but aren't available yet as TEI need to display a link to the UW Madison link from the FRUS metadata file. For example:

- https://history.state.gov/historicaldocuments/frus1861

> ![screen shot 2016-03-16 at 5 39 26 pm](https://cloud.githubusercontent.com/assets/59118/13829572/0eb7ed1c-eb9e-11e5-96d6-dc4c8dfdd4ab.png)

Compare to:

- https://history.state.gov/beta/historicaldocuments/frus1861 or
- http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1861

> ![screen shot 2016-03-16 at 5 40 24 pm](https://cloud.githubusercontent.com/assets/59118/13829590/3179fc1e-eb9e-11e5-9677-0004ed2f5dcc.png)

**Comment by plutonik-a** [comment]
#### Notice for publication with status "under-declassification"
<img width="963" alt="bildschirmfoto 2016-06-12 um 15 22 11" src="https://cloud.githubusercontent.com/assets/1157669/15991377/7fef76be-30b1-11e6-84b6-18d647d1ba17.png">

**Comment by plutonik-a** [comment]
@joewiz 
So far, I only treat the publication-statuses "published" (as default) and "under-declassification" (notice).
What about the other statuses, that can be found in `frus/code-tables/publication-status-codes.xml`?

**Comment by plutonik-a** [comment]
#### Link to 'UW Madison' for published, but non-TEI-available volumes
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1861](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1861)

<img width="687" alt="bildschirmfoto 2016-06-14 um 15 28 13" src="https://cloud.githubusercontent.com/assets/1157669/16044529/1b40e654-3245-11e6-8971-23a9dc2b2fd0.png">

**Comment by plutonik-a** [comment]
@joewiz 
How do we treat volumes with more than one <location> tag?
Some volumes have a link to Worldcat, i.e. `frus/bibliography/frus1864p4.xml`, [https://github.com/HistoryAtState/frus/blob/master/bibliography/frus1864p4.xml#L14](https://github.com/HistoryAtState/frus/blob/master/bibliography/frus1864p4.xml#L14)

I've found these cases:
* Current development, 'Madison' link is displayed, all HTML:
 [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1864p4](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1864p4) 
<img width="500" alt="bildschirmfoto 2016-06-14 um 15 28 13" src="https://cloud.githubusercontent.com/assets/1157669/16044763/084e62d2-3246-11e6-827d-1ac7ebed55fd.png">


* Current live page, 'Madison' link is displayed, notice is rendered as TEI:
[https://history.state.gov/historicaldocuments/frus1864p4](https://history.state.gov/historicaldocuments/frus1864p4)
<img width="500" alt="bildschirmfoto 2016-06-14 um 15 28 27" src="https://cloud.githubusercontent.com/assets/1157669/16044851/61d3e264-3246-11e6-914c-eea1f0c1216a.png">


* Old page, 'Worldcat' link is displayed:
[http://web.archive.org/web/20111017194706/http://history.state.gov/historicaldocuments/frus1864p4](http://web.archive.org/web/20111017194706/http://history.state.gov/historicaldocuments/frus1864p4)
<img width="500" alt="bildschirmfoto 2016-06-14 um 15 28 38" src="https://cloud.githubusercontent.com/assets/1157669/16044911/9e933fc4-3246-11e6-9897-090f9563bdb3.png">

**Comment by joewiz** [comment]
@plutonik-a Regarding https://github.com/eXistSolutions/hsg-shell/issues/154#issuecomment-225432586, we should display the status of all volumes that do not have the status `published`. We should look up the status from https://github.com/HistoryAtState/frus/blob/master/code-tables/publication-status-codes.xml#L6-L25. The text of the status message should be pulled directly from this file and not hard coded in this app. Example code for looking up the status message can be found in https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-html.xqm#L247-L251.

Regarding https://github.com/eXistSolutions/hsg-shell/issues/154#issuecomment-225885068, please see my comment at https://github.com/eXistSolutions/hsg-shell/issues/232#issuecomment-229670249.

**Comment by plutonik-a** [comment]
Non-published volumes show a notice for the readers, consisting of a static part and a dynamic message, pulled from file `code-tables/publication-status-codes.xml`.

---

## Publication Status "Being Researched or Prepared"
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v24](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v24)

<img width="628" alt="bildschirmfoto 2016-08-08 um 17 21 05" src="https://cloud.githubusercontent.com/assets/1157669/17484976/8d68c57c-5d8c-11e6-8a49-5530f0fc330f.png">

##  Publication Status "Being Planned (research has not begun)"
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1981-88v02](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1981-88v02)

<img width="602" alt="bildschirmfoto 2016-08-08 um 17 23 27" src="https://cloud.githubusercontent.com/assets/1157669/17485108/e8cfece2-5d8c-11e6-9d3c-a607135e6bda.png">

##  Publication Status "Under Declassification Review"
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v42](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v42)

<img width="606" alt="bildschirmfoto 2016-08-08 um 17 25 31" src="https://cloud.githubusercontent.com/assets/1157669/17485186/2ab35748-5d8d-11e6-8a16-d788bb0214b5.png">

##  Publication Status "In Production"
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1951-54Iran](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1951-54Iran)

<img width="603" alt="bildschirmfoto 2016-08-08 um 17 28 14" src="https://cloud.githubusercontent.com/assets/1157669/17485302/922e41ee-5d8d-11e6-95fb-cc592558bfa5.png">

**Comment by joewiz** [comment]
@plutonik-a Perfect, it's great to see this one closed!
