### ISSUE TITLE
[frus-history] Missing ebook panel

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#158]
This ebook panel hasn't been implemented so far. 
Is this is intended?
If not, is it OK to contain 2 columns for this page and just stack the two panels into one column on wide screens? Otherwise, the layout won't fit, i.e. because of larger font-sizes.

[https://history.state.gov/historicaldocuments/frus-history](https://history.state.gov/historicaldocuments/frus-history)
[https://history.state.gov/beta/historicaldocuments/frus-history](https://history.state.gov/beta/historicaldocuments/frus-history)

<img width="979" alt="missing-ebook-panel" src="https://cloud.githubusercontent.com/assets/1157669/13984366/ffb9e8c6-f0f5-11e5-9d00-40e5347d619d.png">

**Comment by joewiz** [comment]
@plutonik-a Thank you for catching this! It was not intended. Yes, stacking this panel on top of the "resources" panel is perfect. Could you please add this panel to the frus-history landing page? 

(For reference/contrast, on interior pages such as https://history.state.gov/beta/historicaldocuments/frus-history/research or https://history.state.gov/beta/historicaldocuments/frus-history/research, the book is a link in the panel labelled "publications.")

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/01d10c7db200fa870326de2ef210532f475ddf8b
<img width="800" alt="bildschirmfoto 2016-03-30 um 18 52 53" src="https://cloud.githubusercontent.com/assets/1157669/14150292/ae8e35fc-f6a8-11e5-9cb3-418440393a2e.png">
