### ISSUE TITLE
Pull TEI Simple ebook & PDF generation from public UI

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#16]
For launch, we should just show links to PDFs, ebooks stored on S3 instead of generating them on the fly.

The on-the-fly generation of ebooks needs further testing & style refinement (to conform to house styles) before it's ready.

**Comment by joewiz** [comment]
Page should look like: http://history.state.gov/historicaldocuments/frus1952-54v01p2

Current look: http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v01p2

**Comment by JoernT** [comment]
must this be part of the relaunch milestone?

**Comment by joewiz** [comment]
The PDF output would need to be refined considerably, and ebook outputs (not yet part of UI) would need to be adapted to the existing ebook structure/look. PDF/ebook generation via tei-simple-pm is a valuable feature, but one that shouldn't hold up the release. Instead, we should simply offer links to existing static ebooks and PDFs. So, yes, this issue should be part of the relaunch milestone.

**Comment by joewiz** [comment]
Completed removal, so closing this. Will address need for additional links and refining functionality in a future set of issues.
