### ISSUE TITLE
[departmenthistory] Sidebar navigation is presented as main content

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#161]
I don't know how to handle the layout of this page.

---
Current:
[https://history.state.gov/beta/departmenthistory/buildings](https://history.state.gov/beta/departmenthistory/buildings)

Desired:
[https://history.state.gov/departmenthistory/buildings](https://history.state.gov/departmenthistory/buildings)

---

File:
`pages/departmenthistory/buildings/index.html`

---
<img width="968" alt="departmenthistory-current" src="https://cloud.githubusercontent.com/assets/1157669/14021377/884f580c-f1db-11e5-9d7e-ddabd539ebae.png">

---
<img width="732" alt="departmenthistory-new" src="https://cloud.githubusercontent.com/assets/1157669/14021389/8ff28bc4-f1db-11e5-920c-b3b3edf67133.png">

**Comment by joewiz** [comment]
In general, hsg-shell has abandoned TOCs in sidebars, expecting that readers will make use of breadcrumbs to navigate to the publication's main level's table of contents, or to sub-sections' tables of contents. So while we could probably refine the landing page for this publication to display more than *just* the table of contents, I don't think a TOC sidebar is needed. A sidebar could link to other entries in the Department History section, but I don't have a clear idea in my own head about when we should show such a sidebar.

Does this help with your question?

**Comment by plutonik-a** [comment]
> Does this help with your question?
Yes, thank you. 
I would still add a sidebar with the links to other sections of the Department History.
It should appear on every landing- and sub-page, because those levels are not represented in the main navigation above and are unreachable otherwise. 
The breadcrumb only helps to navigate up and down the levels, never across.

**Comment by joewiz** [comment]
This sounds like a good principle: every landing and sub-page should have a sidebar with links to *other* pages in the same section, to facilitate horizontal navigation *across* levels and complement the breadcrumbs, which only offer vertical navigation. 

My only worry is that when we have other sidebars with content about the current page (e.g., info about people or terms on the page), the navigation sidebar (if shown on top) can push the content-related info sidebar down. Or on a mobile view, a navigational sidebar with too many entries can be too long or unwieldy. 

Could you suggest some guidelines for optimal placement and length of navigational sidebars? Do you have other views/thoughts about this?

**Comment by plutonik-a** [comment]
@joewiz 
> My only worry is that when we have other sidebars with content about the current page (e.g., info about people or terms on the page), the navigation sidebar (if shown on top) can push the content-related info sidebar down.

That's right. This is not an optimal solution, but it's the only one we can support for milestone 1.
But on the other hand, even with this simple solution we are able to gain usability on some pages, were I placed two sidebars instead of just either the main or the related one.

> Do you have other views/thoughts about this?

For the next milestone, I'ld be happy to help facilitating the navigation of your site, which is currently quite difficult because of the deepness of page-levels.
Also, if we know how your users mainly use your site, we are able to create a navigation-pattern that suits the typical use case most and furthermore creates a nicer user experience.

You might want to have a look on Google's specs about navigation patterns to see some possible examples:
https://www.google.com/design/spec/patterns/navigation.html#navigation-patterns

**Comment by joewiz** [comment]
@plutonik-a I agree with your feeling about the limits of what we can accomplish for milestone. I worry that even applying the principle of every landing page & sub-page having a menu with lateral navigation could take quite a bit of work to add to the existing pages. How many pages require this addition? 

Thanks for your offer to help improve navigation for the next milestone. Let's assess resources for this task once we've completed the first milestone. My colleagues have drawn up a proposal for a reorganization of the site, which I can share with you then, and I, for some time, have been itching to flatten the organization of the site and to reduce its depth.

**Comment by plutonik-a** [comment]
I'm right in the middle of it. It's mainly a thinking once and then copy&paste job, because every page is hard coded and not assembled and built by includes.
I have to crawl through the site because of fixing the grid anyway, so it's no big deal in adding a sidebar here and there...

**Comment by joewiz** [comment]
Okay, that sounds good, thank you.  Your point about these being hardcoded reminds me we should think about a more modular approach to sidebars, like we've talked about for breadcrumbs (#153).

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/4fb4981191806466a9eacad136f165f9ab465dcf and https://github.com/eXistSolutions/hsg-shell/commit/81739c91ed6cbb639b4cb617a138e50d31e34c13
