### ISSUE TITLE
List all volumes for an administration, not just those that have been published

### ISSUE THREAD

**Issue by line-o** [eXistSolutions/hsg-shell#162]
Compare
https://history.state.gov/historicaldocuments/reagan
with
https://history.state.gov/beta/historicaldocuments/reagan

**Comment by joewiz** [comment]
Thank you, I made the following change to the old site on Dec. 17 (paho svn rev. 4381):

> list all volumes for an administration, not just those that have been published

I'll to port the changes over to hsg-shell.
