### ISSUE TITLE
[TOC] TOC wrapper in sidebar is generated twice

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#169]
[https://history.state.gov/beta/about/hac/intro](https://history.state.gov/beta/about/hac/intro)

<img width="618" alt="hac-sidebar" src="https://cloud.githubusercontent.com/assets/1157669/14078937/08d3f73c-f4fa-11e5-8785-ad12f338a691.png">

The sidebar is generated from a general TOC function, which causes problems, because
1. the wrapping containers are generated twice
2. the sidebar needs different markup than the general page TOC (a styling **only** for the sidebar is impossible with the current code)

We need a particular TOC-sidebar function/case/module, which returns the markup only for the sidebar.

---
Files: 
`modules/frus-toc-html.xqm`
`pages/about/hac/section.html`

**Comment by plutonik-a** [comment]
In addition, an empty list is generated within each list-item of the TOC, which results in very strange behavior on certain breakpoints.

<img width="313" alt="superfluous-list" src="https://cloud.githubusercontent.com/assets/1157669/14079609/538bb99a-f4ff-11e5-9b01-e20e6551430d.png">

**Comment by joewiz** [comment]
@plutonik-a Assuming you still need this fixed despite the mention in #156, I have two questions:

1. For the duplicate `toc-inner`, is there a reason you don't want to remove the `toc-inner` class from `pages/about/hac/section.html`? 

2. I have a fix for the empty list issue too. Would you like me to push this to the fix-grid-layout branch or master?

**Comment by plutonik-a** [comment]
@joewiz 
1. No, you're right, it can be deleted. But not having a TOC-sidebar module is tricky, because the markup is different for it and it needs some CSS work-around.
2. I think `master` is better, because otherwise I'm running into merge conflicts and I'ld like to finish this PR as quick as possible.

**Comment by plutonik-a** [comment]
This is the problem, I'm actually dealing with:
1. There is a rule in the TOC-code, that looks, if there is a TOC heading. For the sidebar layout, I need a heading container to display the `<h2>`, but there is no way in CSS to dynamically decide, if there is content in it or not. That's why, a TOC-sidebar function would be helpful here.
2. The heading "Table of Contents" is hard-coded and outside the sidebar. Without a heading, the content of the sidebar will be confusing for users.
<img width="336" alt="toc-sidebar" src="https://cloud.githubusercontent.com/assets/1157669/14113720/7b7bd284-f5d4-11e5-8d79-35e4b734caf8.png">

**Comment by joewiz** [comment]
With my commit just now, we have a new function, `toc:table-of-contents-sidebar()`, which you can call via templating:

```xml
<div id="toc" data-template="app:fix-links">
    <div class="hsg-panel" data-template="toc:table-of-contents-sidebar" data-template-heading="false" data-template-highlight="true"/>
</div>
```

It's 100% identical to the original `toc:table-of-contents()` function, except the `<div>` that it produces comes with no `@class` or other attributes, just a naked `<div>` wrapper around the contents. As with the  original function, you can prevent the function returning an inner `<h2>` by setting the `@data-template-heading` templating attribute to `false`.

If I've gotten any of your needs here wrong, let me know.

**Comment by joewiz** [comment]
With d0907d2a, a `<div data-template="toc:table-of-contents-sidebar" data-template-heading="false" data-template-highlight="true"/>` will return:

```
<aside class="hsg-width-sidebar">
    <div class="hsg-panel">
        <div class="hsg-panel-heading">
            <h2 class="hsg-sidebar-title">Table of Contents</h2>
        </div>
        <ul class="hsg-list-group">
            <li class="hsg-list-group-item">...</li>
        </ul>
    </div>
</aside>
```

`Table of Contents` will be used if `@data-template-heading` is `false` or if the `toc:table-of-contents` function returns no heading.
