### ISSUE TITLE
Fix 404 pages, test 404 scenarios

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#17]
We have both error-page.html and a 404.html.  The appearance of error-page.html is better, I think, so remove 404.html and all calls to it.

http://localhost:8080/exist/apps/hsg-shell/test-page-responses.xql shows that certain pages return a 400 instead of 404.  We shouldn't be issuing 400 errors, only 404s (right?).

Test each section & subsection to make sure that unknown resources (e.g., /blah, /section/blah, /section/subsection/blah) correctly return 404 codes.

**Comment by tuurma** [comment]
Don't you think 404 is in general a helpful bit of information? Made 404 look more like error page, hope that helps.

**Comment by joewiz** [comment]
@tuurma Thanks! I think you've successfully eliminated the 400 errors.  As to the design and message, could you please follow the error page at http://history.state.gov/blah?  

> ![screen shot 2015-11-11 at 11 40 14 pm](https://cloud.githubusercontent.com/assets/59118/11110727/98cb19b8-88cd-11e5-883c-6bfc638ab1f5.png)

I'm certainly open to ideas for improvement :)

Lastly, I still see both an error-page.html and a 404.html.  Could you decide on one (I'm guessing error-page.html is the more versatile), and delete the other?  I was actually the one to add the 404.html page originally because I saw it referenced somewhere in one of the original files in the app, but this was before I understood error-page handling in the templating framework.

**Comment by tuurma** [comment]
Ah, thanks for pointing out the look of the page you are after.

As for 404/error-page, I was wondering if showing a bit different error messages for real 'not found' as opposed to general error page 'because of whatever' wouldn't be helpful. There seem to be quite a lot of resources that actually are not available (like a number of volumes from Truman administration, eg http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v03), even though there are links pointing to them. What do you think?

**Comment by joewiz** [comment]
Thanks for pointing out the issue with pages like frus1945v03 - which are for volumes published in print that we haven't completed digitizing yet and should show a more friendly message.  Compare http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v03 with http://history.state.gov/historicaldocuments/frus1945v03.  I need to add handling for this!

**Comment by wolfgangmm** [comment]
I dropped 404.html in favour of error-page.html. In most situations, entering an invalid path should now lead to a 404. Only the issue mentioned by @joewiz in the comment above remains.

**Comment by joewiz** [comment]
@wolfgangmm Great. Could you suggest the best templating approach for modifying pages/volume-landing.html to display the links to the UW Madison or WorldCat copies of a volume (drawing on the `bibliography` collection) if the volume is not available yet in TEI? Right now the template calls `pages:header` and `toc:table-of-contents`. These throw errors if there's no corresponding TEI volume available. Should I just replace this with a `<div data-template="my:check-if-volume-is-available-and-show-it-if-so-otherwise-show-links">` which uses XQuery to figure out what to show? 

If there's an existing templating solution, I'll use it. Otherwise, I'll go with the XQuery approach.

**Comment by joewiz** [comment]
Perhaps I'll close this and add a new issue targeted at this question.
