### ISSUE TITLE
[Milestones chapters] Navigation with arrows isn't helpful

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#170]
[https://history.state.gov/beta/milestones/1750-1775/french-indian-war](https://history.state.gov/beta/milestones/1750-1775/french-indian-war)

Current behavior: 
You can swipe through the chapters in milestones, but the output for the user won't change.
Only the URL changes.

<img width="800" alt="milestones-chapters" src="https://cloud.githubusercontent.com/assets/1157669/14105056/73a645d8-f5a9-11e5-82a7-36f82d7b56c8.png">

Suggestion:
I would like to add a TOC-sidebar like on the old page and display the whole contents on on page. Also, I could add a "back-to-top" arrow.

<img width="800" alt="milestones-sidebar" src="https://cloud.githubusercontent.com/assets/1157669/14105310/1e5baad0-f5ab-11e5-9c82-74d7ab62f284.png">

**Comment by wolfgangmm** [comment]
For the page you referenced, arrow navigation is buggy for sure and needs to be fixed. I think I know what it is.

Showing the entire content of a milestone on one page would be possible for this example, because the content is short enough. For other pages that's not a good idea as loading the page might just take too long.

**Comment by plutonik-a** [comment]
There is another way to fix it:
We show the overview with the TOC content without the arrows, display a sidebar with the second level navigation - like a landing page - and start with the arrow navigation when displaying the chapters.

I noticed that we did it like this i.e. on [https://history.state.gov/beta/departmenthistory/buildings](https://history.state.gov/beta/departmenthistory/buildings).

**Comment by plutonik-a** [comment]
Turned template into a landing page: The arrow navigation is skipped on this page and is used on subpages.

### Milestones Landing Page
<img width="800" alt="milestones-overview" src="https://cloud.githubusercontent.com/assets/1157669/14143188/369eab12-f68a-11e5-81ec-e55f742b0303.png">

### Milestones Subpage
<img width="800" alt="milestones-subpage" src="https://cloud.githubusercontent.com/assets/1157669/14143194/48cfcb40-f68a-11e5-8594-adc46dbdc6db.png">


Fixed with https://github.com/eXistSolutions/hsg-shell/commit/4d4fdd61afe710193d02b677e2babf0faab058e6
