### ISSUE TITLE
[FRUS] Volume is missing, different wording

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#171]
Compare
[https://history.state.gov/beta/historicaldocuments/frus1861](https://history.state.gov/beta/historicaldocuments/frus1861)

<img width="514" alt="bildschirmfoto 2016-03-29 um 12 55 46" src="https://cloud.githubusercontent.com/assets/1157669/14105764/d7d54e56-f5ad-11e5-82bd-6757333ec1e7.png">

with
[https://history.state.gov/historicaldocuments/frus1861](https://history.state.gov/historicaldocuments/frus1861)

<img width="514" alt="bildschirmfoto 2016-03-29 um 12 55 40" src="https://cloud.githubusercontent.com/assets/1157669/14105740/ac68457a-f5ad-11e5-8a41-ca1122d68fa2.png">

**Comment by joewiz** [comment]
Dupe of #154?

**Comment by plutonik-a** [comment]
Oh, you're right. I'll close this.
