### ISSUE TITLE
Performance: limit query results

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#178]
Most queries on hsg may easily produce more than 10000 hits. The lucene query is not a problem, but filtering out "wrong" hits (i.e. those without @xml:id or child divs with @xml:id) does add about 50% to the query time. I tried to speed this up, but it is difficult if the result set contains 90000 hits or more.

But I now ask myself: does anybody really want to browse through > 1000 hits? Wouldn't it be sufficient to just show the total number of hits and add a note that browsing will be limited to the first 1000? This way I could guarantee fast response times as shown by stress tests. The alternative would be to hack the lucene index, but that's a bigger job.

**Comment by joewiz** [comment]
Wow, what an interesting finding. I think it is reasonable to limit results to 1,000. 

Another alternative would be to "pre-chunk" the TEI files into documents that are the actual unit of search. I can imagine other uses of this: to improve performance of pagination, of TOCs, etc. 

But for now, limiting results to 1,000 sounds good.
