### ISSUE TITLE
Images and videos in frus1917-72PubDip not loading

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#18]
http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1917-72PubDip/appendix-5

vs. 

http://history.state.gov/historicaldocuments/frus1917-72PubDip/appendix-5

Granted, the approach here - embedding HTML video tags inside this TEI file - was awful, but we will need a way to have this video display. 

Odd, too, that the images don't display:

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1917-72PubDip/appendix-6

vs.

http://history.state.gov/historicaldocuments/frus1917-72PubDip/appendix-6

**Comment by tuurma** [comment]
@wolfgangmm changes to tei-simple that allow pass-through of xhtml elements take care of embedded videos, images are also fixed by one of his commits earlier today. Beware, a little bit is missing from the commit to tei-simple so now all page processing is broken, bear with us a moment.

**Comment by tuurma** [comment]
Ok, it's fixed now.

**Comment by joewiz** [comment]
Thanks, I can now see the video!  The rightmost portion of the video appears to be cut off.  Would you suggest that I modify the dimensions of the video to fit?

> <img width="645" alt="screen shot 2015-11-15 at 5 54 05 pm" src="https://cloud.githubusercontent.com/assets/59118/11171776/9f753324-8bc6-11e5-9cd5-6ccf6495391e.png">

Also, the image link here is broken.  The link is http://s3.amazonaws.com/static.history.state.gov/frus/frus1917-72PubDip/Document%20A.5 but should be http://s3.amazonaws.com/static.history.state.gov/frus/frus1917-72PubDip/Document%20A.5.png.

**Comment by wolfgangmm** [comment]
The max width of the content is 530px in the current layout, so video width should probably be limited to that.

**Comment by joewiz** [comment]
@wolfgangmm Great, I've updated the width for this volume in SVN and will push the updated file to github with the next FRUS update later this month. Thanks for these fixes!
