### ISSUE TITLE
[Pre-1861/Serial Set] Restructure templates

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#182]
1. A breadcrumb is missing for page-type serial-set:
    `pages/historicaldocuments/pre-1861/serial-set/index.html`
<img width="500" alt="bildschirmfoto 2016-04-07 um 11 30 38" src="https://cloud.githubusercontent.com/assets/1157669/14346813/380a9ec2-fcb4-11e5-9508-09d49b9e77f6.png">

2. Remove old sidebar with dropdowns for administration and volume selection and add new navigation sidebar without the volume selection
<img width="150" alt="bildschirmfoto 2016-04-07 um 11 31 23" src="https://cloud.githubusercontent.com/assets/1157669/14346847/653b0558-fcb4-11e5-9e71-1ab041c54d79.png">

3. Arrange long content lists in clear and responsive column layout

4. Delete bullets from list `serial-set:region-subject-list`

---

[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/pre-1861/serial-set](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/pre-1861/serial-set)
[https://history.state.gov/beta/historicaldocuments/pre-1861/serial-set](https://history.state.gov/beta/historicaldocuments/pre-1861/serial-set)

Files:
`pages/historicaldocuments/pre-1861/index.html`
`pages/historicaldocuments/pre-1861/serial-set/index.html`
`pages/historicaldocuments/pre-1861/serial-set/browse.html`
`pages/historicaldocuments/pre-1861/serial-set/all.html`

**Comment by plutonik-a** [comment]
Also fixed with:
https://github.com/eXistSolutions/hsg-shell/commit/bcda4dd28c1256e2c058a6fb67e561f49b95b9a0
https://github.com/eXistSolutions/hsg-shell/commit/581d9f5b274ae2847db22b9c2572a937de844a6f
https://github.com/eXistSolutions/hsg-shell/commit/f0244e3efe336fd89b58c369bfdd69a48b18fff0
https://github.com/eXistSolutions/hsg-shell/commit/6c578a924ae34d77efc8d5c7a7a6a10f76a3eafa

**Comment by plutonik-a** [comment]
### Result
**1. Breadcrumb**
<img width="500" alt="bildschirmfoto 2016-04-07 um 16 37 04" src="https://cloud.githubusercontent.com/assets/1157669/14354810/0444602a-fcdf-11e5-90a1-97fbeac5b919.png">

**2. Sidebar**
<img width="500" alt="bildschirmfoto 2016-04-07 um 16 34 18" src="https://cloud.githubusercontent.com/assets/1157669/14354852/32923d58-fcdf-11e5-8b9f-d4e61e34ae14.png">

**3. List in columns **
Couldn't find an acceptable CSS solution (even tried flexbox layout), because the lists are generated without being able to sort them into column wrappers. In addition, they have completely different heights, so it's impossible to tile them properly.

**4. List Regions and Sections without bullets**
<img width="300" alt="bildschirmfoto 2016-04-07 um 16 36 09" src="https://cloud.githubusercontent.com/assets/1157669/14354987/c88a6c72-fcdf-11e5-8255-39bf6d9f1bd8.png">

**Comment by plutonik-a** [comment]
@line-o Could you please try to upgrade the function [ssh:region-and-subject-link](https://github.com/eXistSolutions/hsg-shell/commit/6c578a924ae34d77efc8d5c7a7a6a10f76a3eafa#diff-51d77fb8db75e44ca4cef7854a197dd3R61) in file ` modules/serial-set-html.xqm` with the missing URL-logic for `$subject`?

**Comment by joewiz** [comment]
This is a great improvement @plutonik-a. 

Regarding item 3, is the problem that the 5-column table is simply too wide? Would a different presentation of the material facilitate a responsive view of this information? If so, perhaps we could reformat the table.

**Comment by plutonik-a** [comment]
@joewiz 
> Regarding item 3, is the problem that the 5-column table is simply too wide? 

No, the problem here is the list on page [https://history.state.gov/historicaldocuments/pre-1861/serial-set](https://history.state.gov/historicaldocuments/pre-1861/serial-set). 
The current logic/code generates just one list with nested sublists.

But as you mentioned the table, yes, it needs a little improvement considering the column width.
With a bit more effort, I can change the table to behave adaptive, meaning the cells/content will reorder depending on screen width.

**Comment by joewiz** [comment]
@plutonik-a Ah, of course, that was the URL you provided. Now I understand what you mean by "tiling" them - you had hoped to place the 5 lists on page into 2+ columns. I can see why this is difficult to do automatically. If this were a more frequently used page I'd suggest that we break the list into two groups of 2 and 3, to be placed into two columns - perhaps for a future pass through the site.
