### ISSUE TITLE
Combine external javascript / apply PageSpeed Insights

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#190]
Running Chrome's Developer Tools > Audits, it suggests combining javascript files into one: app.js, bootstrap.js, jquery.js, and jquery.touchSwipe.js. Please combine and minify these javascript files with gulp (presumably) and update `hsg-shell/templates/site.html` to point to the combined/minified version.

On a related note, `hsg-shell/templates/site.html` still references non-minified versions of these files from `bower-components`, while gulp is already minifying and storing them in `resources/scripts/vendor`. Assuming we are ready to move away from `bower-components`, please update `hsg-shell/templates/site.html`.

(Would you recommend we combine/minify `resources/css/main.css` and `resources/odd/compiled/frus.css`?)

**Comment by joewiz** [comment]
Google's PageSpeed Insights nicely summarizes these issues at https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fhistory.state.gov.

**Comment by joewiz** [comment]
Re: PageSwipe, see #212.

**Comment by joewiz** [comment]
Please add the `async` attribute to scripts where possible. Confirmed possibility: the DAP tracker at https://github.com/eXistSolutions/hsg-shell/blob/master/templates/site.html#L315. See https://github.com/digital-analytics-program/gov-wide-code/issues/41.

**Comment by line-o** [comment]
This update needs a environment variable to be set on the production machines (or at the time of building the XAR) to take effect.

**Comment by joewiz** [comment]
@line-o I successfully built the "production" version and can confirm the assets are minified. Please let me know when this is deployed to hsg.
