### ISSUE TITLE
Mobile screen size: Header image overrides beta ribbon link

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#196]
On my iPhone 6S and Chrome Developer Tools > device mode > phone sizes, clicking on the ribbon "About the beta" link doesn't take you to that page; instead, the link goes to the homepage. Is there a way to ensure the ribbon link is the "top-most" link (z-index, perhaps)?

**Comment by joewiz** [comment]
@plutonik-a Could you confirm this fixes the problem for you? For me on Chrome and Safari, at phone sizes when the ribbon is horizontal (as opposed to diagonal), the ribbon doesn't show have any .ribbon-container properties, and when I try to click on it, the link goes to the homepage.

**Comment by joewiz** [comment]
Here's a screenshot from Safari:

> ![latest_news_-_now_available__foreign_relations_of_the_united_states__1981 1988__volume_iii__soviet_union__january_1981 january_1983_-_now_available__frus__1981 1988__volume_xiii__conflict_in_the_south_atlantic__1981 1984_-_now_available__fr](https://cloud.githubusercontent.com/assets/59118/14787052/c9b4930e-0acf-11e6-97dc-f438b738921e.png)

**Comment by plutonik-a** [comment]
@joewiz 
Thanks for reviewing this. It seemed to work, when I closed the issue.
I tested it in an emulator and on an Android phone and it looks ok now.

![ribbon](https://cloud.githubusercontent.com/assets/1157669/14797860/0e6d6e3e-0b35-11e6-913e-f3c8c4d83a59.gif)
