### ISSUE TITLE
ajax navigation broken on new servers

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#197]
It appears that the link to frus-ajax.xql is relative instead of absolute. For example, on this page:

  https://52.200.115.76/historicaldocuments/frus1981-88v13/d1

The "next page" link tries to fetch this:

  https://52.200.115.76/historicaldocuments/frus1981-88v13/ch1/modules/frus-ajax.xql?url=%2Fhistoricaldocuments%2Ffrus1981-88v13%2Fd30

Instead of:

  https://52.200.115.76/modules/frus-ajax.xql?url=%2Fhistoricaldocuments%2Ffrus1981-88v13%2Fd30

**Comment by joewiz** [comment]
Would the functional tests catch this error?

**Comment by wolfgangmm** [comment]
I was just looking into this. I wonder how you avoided the issue on /beta? As far as I can see, pages:app-root needs to take nginx-request-uri into account.

**Comment by joewiz** [comment]
I don't recall having done anything special to avoid the issue on /beta. 

Thanks for finding a solution/workaround!

**Comment by wolfgangmm** [comment]
Fixed via https://github.com/eXistSolutions/hsg-shell/commit/671312fec2e2b525e6b1bb6f3a6c4f4cdd4fe622
