### ISSUE TITLE
Fix locale for date formats

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#200]
On pages where dates are rendered, the locale appears to be affecting the date format. For example, see https://52.20.198.114/departmenthistory/travels/president/roosevelt-franklin-d:

> ![screen shot 2016-04-23 at 10 09 17 pm](https://cloud.githubusercontent.com/assets/59118/14765118/97c2dd90-09a0-11e6-8009-a0c53f997d40.png)

FYI the code that generates these dates is https://github.com/eXistSolutions/hsg-shell/blob/master/modules/travels-html.xqm#L159-L171.

**Comment by patczar** [comment]
Done. Always using en-US.

**Comment by patczar** [comment]
Corrected (the language of dates) also on 'visits' page and in some texts related to ebooks.

**Comment by joewiz** [comment]
Great, thanks, Patryk!
