### ISSUE TITLE
"Previous" navigation arrow follows ancestor axis instead of previous

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#204]
The "previous" button on https://history.state.gov/historicaldocuments/frus1969-76v17/d116 should lead to d115, but instead leads to d102 - the first child div of the first ancestor. From d102, "previous" leads to ch3. From ch3, "previous" leads to comp1. 

I've only tested this document in FRUS but assume it affects other documents/volumes/publications.

**Comment by plutonik-a** [comment]
I tested the bug and can confirm, that the "previous" button leads to the first div of the first ancestor until you reach the very first div of the document.
I.e. [https://history.state.gov/historicaldocuments/frus1964-68v01/d1](https://history.state.gov/historicaldocuments/frus1964-68v01/d1).

On top of that, on some occasions navigating back stopped and only worked again after reloading the page.
