### ISSUE TITLE
[frus] Only show "search within" when TEI available; and "download" panels when pdf/ebooks available

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#208]
Example of page with no TEI or pdf/ebooks (please remove both "search within" and "download" pane): https://history.state.gov/historicaldocuments/frus1919v01 

> ![screen shot 2016-04-29 at 11 02 12 am](https://cloud.githubusercontent.com/assets/59118/14920099/dba3ec4a-0df9-11e6-9097-e190e22d8a2a.png)

Example of page with TEI but no pdf/ebooks (please remove "download" pane): https://history.state.gov/historicaldocuments/frus1952-54v07p1

Example of page with PDF but no TEI or ebooks: None currently, but this case often happens when we first publish a book. We post the PDF but don't yet have the TEI or ebook right at publication time.

**Comment by plutonik-a** [comment]
Similar solution: https://github.com/eXistSolutions/hsg-shell/commit/05a53f4e7d2a053c78a359d3473858b9940e12cd

**Comment by plutonik-a** [comment]
Files:
* Template with search sidebar: `pages/historicaldocuments/volume-landing.html`
* Module: `modules/frus-html.xqm`

**Comment by joewiz** [comment]
@plutonik-a Likewise, this seems to do the trick, thank you!

**Comment by plutonik-a** [comment]
#### Without `tei:text` node
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1919v01](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1919v01)
<img width="299" alt="bildschirmfoto 2016-05-27 um 22 17 47" src="https://cloud.githubusercontent.com/assets/1157669/15620172/e7f50d7e-2458-11e6-99d7-4bd246a36d17.png">

#### Without media to download
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01)
<img width="305" alt="bildschirmfoto 2016-05-27 um 22 17 37" src="https://cloud.githubusercontent.com/assets/1157669/15620176/efb065ea-2458-11e6-82a9-6d3da2f3df88.png">

#### With text and media
[https://history.state.gov/historicaldocuments/frus1952-54v01p1](https://history.state.gov/historicaldocuments/frus1952-54v01p1)
<img width="306" alt="bildschirmfoto 2016-05-27 um 22 17 20" src="https://cloud.githubusercontent.com/assets/1157669/15620185/f880fb44-2458-11e6-8fda-3faabbd2b0c0.png">

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/236

**Comment by plutonik-a** [comment]
Also fixed with https://github.com/eXistSolutions/hsg-shell/commit/67e71f27cfd32b9e3576c586fde7e213c9a79859
