### ISSUE TITLE
site review

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#21]
This is a list of issues I noticed while clicking around on the site. (Only a start.) Feel free to add more items in comments.

http://localhost:8080/exist/apps/hsg-shell/
- [x] complete homepage

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments
- [x] fix generic `<title>`
- [ ] fix body table showing administrations is not great
- [ ] fix right sidebar list bullets

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v01
- [ ] show Madison link as on http://history.state.gov/historicaldocuments/frus1945v01
- [ ] show tags right sidebar
- [ ] 404 pages should show custom `<title>`

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1948v01p1
- [ ] add links to S3 (PDF, Ebook) in right sidebar
- [ ] increase handing indent for body TOC lists - double it or match indent for "Editor:" list item

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1948v01p2/d1
- [ ] add right sidebar links to page image view
- [ ] `h1` title should span the full width of the container div, like the `<hr>`; it's indented too much
- [ ] increase padding around volume title in left sidebar TOC

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/about-frus
- [x] fix generic `<title>`

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history
- [ ] eliminate bullet points for publication info and TOC (in body)
- [ ] link to events in left sidebar are broken; apply app:fix-links

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/introduction
- [ ] body not loading
- [ ] `pages:title()` is returning `/text()`, so italicized FRUS title is dropped

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/chapter-2
- [ ] `toc:toc-head()` is choking on the double-head element. probably need a frus-history ODD.

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/documents/1959-11-06-hac-meeting-minutes
- [ ] add frus-history section links to left sidebar 
- [ ] add breadcrumbs
- [ ] add prev/next links
- [ ] fix partial `<title>`
- [ ] fix rendering of "Present:" in list of those present at the meeting
- [ ] fix footnotes, which aren't appearing in pop-up - see http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/documents/1964-11-06-hac-meeting-minutes#fnref:3.2.1.2.6.1.2.4.2
- [ ] also noticed that clicking on a link to footnote text isn't updating the URL bar

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/an-outburst-of-pamphlets
- [ ] images not working
- [ ] add breadcrumbs

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/events
- [ ] remove bullet from left sidebar frus-history link

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/ebooks
- [x] fix S3 to populate full list
- [ ] fix awful looking page title - highlighted "EBooks" (and change to "Ebooks")
- [ ] fix height of images; they appear stretched

http://localhost:8080/exist/apps/hsg-shell/departmenthistory
- [ ] add missing left sidebar
- [x] fix partial `<title>`

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history
- [x] NOT WORKING

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/secretaries
- [ ] add missing left sidebar
- [x] fix partial `<title>`

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/dulles-john-foster
- [ ] move secretary bio into body, position info into sidebar
- [ ] add missing left sidebar
- [x] fix partial `<title>`

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/principals-chiefs
- [ ] fix weird headings - Introduction is gray shadowed, others are bigger
- [ ] improve spacing between definition lists
- [x] fix partial `<title>`

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/principalofficers
- [ ] add missing left sidebar
- [ ] fix partial `<title>`
- [ ] remove list bulleting

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/principalofficers/assistant-secretary-for-european-affairs
- [x] ERROR (cannot compare operands: xs:integer and xs:string)

**Comment by joewiz** [comment]
Need to apply `<title>` implementation from https://github.com/eXistSolutions/hsg-shell/issues/15:

Pages that are missing this completely:

/historicaldocuments itselft
/historicaldocuments/status-of-the-series
/historicaldocuments/frus-history
/historicaldocuments/ebooks

And others that have the generated title, but it's not what it should be, typically missing publication titles etc:
/departmenthistory
/milestones
/countries
/about

**Comment by JoernT** [comment]
must be broken down into single tickets

**Comment by joewiz** [comment]
http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/by-name

- [ ] fix styling of A-Z links - to look like http://history.state.gov/departmenthistory/people/by-name

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/by-name/a

- [ ] fix previous next nav button styling - to look like http://history.state.gov/departmenthistory/people/by-name/a

**Comment by joewiz** [comment]
http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history

- [ ] sidebar navigation is slightly out of step with http://history.state.gov/departmenthistory/short-history - in particular, the landing page or top-level chapters should show the first, xml-id-less div. need to study further.

**Comment by joewiz** [comment]
http://localhost:8080/exist/apps/hsg-shell/

- [ ] no `<title>`

**Comment by joewiz** [comment]
Closing with the intention of breaking these issues down in separate issues.
