### ISSUE TITLE
Excessive caching

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#210]
Since moving to hsg3, browsers are caching pages for days - apparently, indefinitely - rather than requesting a fresh copy.  I can't exactly understand why, but it must relate to the response headers.  Here are the response headers from my request just now, at 13:57 GMT:

```
HTTP/1.1 304 Not Modified
Cache-Control: no-cache
Created: Wed, 27 Apr 2016 08:43:50 GMT
Date: Thu, 05 May 2016 13:57:54 GMT
Expires: Thu, 28 Apr 2016 08:43:50 GMT
Last-Modified: Wed, 27 Apr 2016 08:43:50 GMT
Server: nginx/1.8.1
Connection: keep-alive
```

Note that "last modified" is reported as last Wednesday at 8:43.  

The request from my browser:

```
GET / HTTP/1.1
Host: history.state.gov
Connection: keep-alive
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
If-Modified-Since: Wed, 27 Apr 2016 08:43:50 GMT
```

So because hsg is saying the page hasn't been modified since last Wednesday at 8:43, browsers are never refreshing the page. 

I'd appreciate your help getting to the bottom of this issue.  Some useful resources: 

- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
- https://jakearchibald.com/2016/caching-best-practices/.

I would expect our server to tell browsers to cache the HTML for a page for, say, 5 minutes.  For static resources this could be longer, say, 24 hours.

**Comment by tasmo** [comment]
Adjusted the "expires" parameter to "12h".

**Comment by joewiz** [comment]
Thanks, @tasmo. Could you confirm the following results are as expected?

```
$ curl -I https://history.state.gov
HTTP/1.1 200 OK
Cache-Control: max-age=43200
Cache-control: no-cache="set-cookie"
Content-Length: 22904
Content-Type: text/html;charset=UTF-8
Created: Wed, 27 Apr 2016 08:43:50 GMT
Date: Tue, 10 May 2016 14:12:21 GMT
Expires: Wed, 11 May 2016 02:12:21 GMT
Last-Modified: Wed, 27 Apr 2016 08:43:50 GMT
Server: nginx/1.8.1
Set-Cookie: JSESSIONID=1inmnhskhikih1l850mm8zkjwy;Path=/exist;Secure
Set-Cookie: AWSELB=DF3DF3131A3B5A346363EB1AB82654160644E8227C3961D3F003703786C0E52447DA3723B6A192BECC93A380DCC30525256BA2F6416763ADC2F553BFD3E4B5750299775BB7;PATH=/
X-Proxy-Cache: HIT
X-XQuery-Cached: true
Connection: keep-alive
```

The key entries are:

```
Date: Tue, 10 May 2016 14:12:21 GMT
Expires: Wed, 11 May 2016 02:12:21 GMT
```

Two questions:

1. Is there a reason you used 12 hours instead of 5 minutes?

2. Note the duplicate `Cache-Control` and `Cache-control` entries - with different values.

**Comment by joewiz** [comment]
I could add a 3rd:

3. Could you confirm this is an across-the-board setting for all resources served up by nginx, and there is no distinction currently between HTML and static (jpg, css, etc.) resources?

**Comment by tasmo** [comment]
1. No, 12h was just a test. Now its 5 minutes.
2. Don't know where the double Cache-control is coming from. Tested it without header setting with no change.
3. As far as we decided yet; yes. It depends on the creation and change time.

**Comment by joewiz** [comment]
@tasmo Great, thanks! This is much improved, and gives us some possible directions for future improvements.
