### ISSUE TITLE
[frus] Missing description of a term

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#214]
Most terms and abbreviations sidebars appear to be working correctly, but in the case of https://history.state.gov/historicaldocuments/frus1955-57v15/d162, hovering over the term `BG` shows nothing:

> ![screen shot 2016-05-09 at 9 16 58 am](https://cloud.githubusercontent.com/assets/59118/15114391/c3ee41d8-15c7-11e6-92d3-341d01c21af9.png)

Compare to the old site:

> ![screen shot 2016-05-09 at 9 16 46 am](https://cloud.githubusercontent.com/assets/59118/15114394/cb69ed4a-15c7-11e6-896d-6ef295ea9726.png)

My guess is that the issue has something to do with Ben Gurion being tagged with `<persName>`, whereas most terms are simply direct child text nodes.

**Comment by plutonik-a** [comment]
Related https://github.com/eXistSolutions/hsg-shell/issues/213

**Comment by plutonik-a** [comment]
<img width="310" alt="bildschirmfoto 2016-05-26 um 17 45 34" src="https://cloud.githubusercontent.com/assets/1157669/15581386/5fbb6fb2-236c-11e6-9fe2-23af496c527c.png">

<img width="316" alt="bildschirmfoto 2016-05-26 um 17 45 47" src="https://cloud.githubusercontent.com/assets/1157669/15581404/753b3d5e-236c-11e6-9397-c6ba9caa250f.png">

**Comment by joewiz** [comment]
@plutonik-a This seems to do the trick, thanks!
