### ISSUE TITLE
[milestones] Placeholder text for "withdrawn" articles

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#216]
Milestones articles marked with `div/@subtype="removed-pending-rewrite"`, such as, https://github.com/HistoryAtState/milestones/blob/master/chapters/1866-1898.xml#L568, should display the following message:

> Notice to readers: This article has been removed pending review to ensure it meets our standards for accuracy and clarity. The revised article will be posted as soon as it is ready. In the meantime, we apologize for any inconvenience, and we thank you for your patience.

See this screenshot from the old site:

> ![screen shot 2016-05-09 at 12 56 36 pm](https://cloud.githubusercontent.com/assets/59118/15120842/963857f6-15e5-11e6-9f8c-71a626630ba9.png)

Currently the page is empty beneath the heading. See https://history.state.gov/milestones/1866-1898/hawaii:

> ![screen shot 2016-05-09 at 12 58 05 pm](https://cloud.githubusercontent.com/assets/59118/15120864/b36b490a-15e5-11e6-818b-90ac7eb67211.png)

**Comment by plutonik-a** [comment]
List of affected pages:
- milestones/1945-1952/korean-war-2
- milestones/1989-1992/strategic-arms-reduction
- milestones/1953-1960/cento
- milestones/1977-1980/trilateral-diplomacy
- milestones/1866-1898/hawaii

**Comment by plutonik-a** [comment]
This PR is ready to be reviewed and merged.
