### ISSUE TITLE
Search pagination issues

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#217]
Following on from #207, there are still a few search pagination bugs:

1. On https://history.state.gov/search?q=immigration&volume-id=frus1977-80v02, the `»` (next) button is disabled even though there is a page `2`.  
2. The link for the `»` (next) button is lacking the `?start=10` parameter. 
3. On page `2`, the page `1` link is highlighted as `.active`, whereas page `2` should have this class.

**Comment by wolfgangmm** [comment]
Should be fixed by https://github.com/eXistSolutions/hsg-shell/commit/f08e8831b928c8beaf5f4389cbfc9f2eb4c54631
