### ISSUE TITLE
Restore Metagrid

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#218]
hsg is a partner with [Metagrid](http://www.metagrid.ch/), a project for the online networking of humanities resources, such as people. The beta inadvertently dropped metagrid, and we should restore it. Specifically:

Pages showing the roles of individuals such as https://history.state.gov/departmenthistory/people/root-elihu in the `departmenthistory/people` section should load the metagrid javascript snippet (our version is below and at https://s3.amazonaws.com/static.history.state.gov/js/concordances.js; see documentation at http://www.metagrid.ch/en/how-to/, which we could certainly draw from if needed):

```javascript
$(document).ready(function () {
    
    // perhaps the regexp could be more strict and accept only lowercase characters and hyphen?
    // something like:
    // var personId = window.location.href.match(/\/departmenthistory\/people\/([a-z\-]+)$/i);
    var personId = window.location.href.match(/\/departmenthistory\/people\/([^/#]+)$/i);
        
    $.getJSON('https://api.metagrid.ch/widget/history-state/person/' + personId[1] + '.json?lang=en&include=true&jsoncallback=?', function (data) {
        if (data[0]) {
            $("#metagrid").show();
            
            $.each(data[0], function (index, value) {
                $('<li>').attr({
                    class: 'metagrid'
                }).append('<a>').appendTo('#metagrid-container');
                $('#metagrid-container li:last-child a').attr({
                    title: value.short_description, href: value.url
                }).text(index);
            });
        }
    });
});
```

And we need the corresponding HTML snippet for the script to insert the content into. The old site had this corresponding snippet in the sidebar shown in the display of individual person's roles, e.g. :

```
<div id="metagrid" style="display: none" class="resources bordered">
    <h3 id="metagrid-headline">Links from Metagrid.ch (beta)</h3>
    <ul id="metagrid-container"></ul>
</div>
```

**Comment by plutonik-a** [comment]
@joewiz 
Where should the Metagrid widget be implemented on `pages/departmenthistory/people/person.html`?
In the sidebar?

**Comment by joewiz** [comment]
That's correct!  Here's an example:

> ![elihu_root_-_people_-_department_history_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/15361412/6049e3a2-1cdf-11e6-856c-10b5c704a882.png)

**Comment by plutonik-a** [comment]
<img width="732" alt="bildschirmfoto 2016-05-18 um 16 42 48" src="https://cloud.githubusercontent.com/assets/1157669/15363322/aa32e516-1d18-11e6-9249-70650af41cd3.png">

Todo:
Hide widget, if no data is available.

**Comment by joewiz** [comment]
Looks great, and the placement is correct. 

I agree, the widget should not be displayed if there is no data. Since this issue is closed, do you need me to open a new issue with this requirement?

**Comment by plutonik-a** [comment]
> do you need me to open a new issue with this requirement?

Yes please, that would be nice.
