### ISSUE TITLE
Improve print CSS

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#219]
From a reader:

> Contrary to the previous version, the beta version does not seem to be very printer friendly, at least not on my Firefox and Safari browsers.

See the submitted attachment as an example: [Aperçu de « Foreign Relations of the United States, 1961–1963, Volume XII, American Republics - Office of the Historian ».pdf](https://github.com/eXistSolutions/hsg-shell/files/257816/Apercu.de.Foreign.Relations.of.the.United.States.1961.1963.Volume.XII.American.Republics.-.Office.of.the.Historian.pdf)

A print-friendly view should contain only the logo and body, suppressing all navigation elements.

**Comment by plutonik-a** [comment]
Replace media on following pages with screenshots:

* [https://history.state.gov/departmenthistory/diplomatic-couriers](https://history.state.gov/departmenthistory/diplomatic-couriers)
* [https://history.state.gov/historicaldocuments/frus-history/appendix-a](https://history.state.gov/historicaldocuments/frus-history/appendix-a)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/226
