### ISSUE TITLE
Hide Metagrid sidebar widget unless API returns data

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#228]
See discussion in #218: https://github.com/eXistSolutions/hsg-shell/issues/218#issuecomment-220060491. 

(Also related: #208. The similarity is that certain sidebars should be hidden unless data is available to support their content/function.)

**Comment by joewiz** [comment]
This is a blocker on deployment of the master code and its other recent improvements, so I'll increase the priority.

**Comment by plutonik-a** [comment]
With data:
[http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/root-elihu](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/root-elihu)

<img width="500" alt="bildschirmfoto 2016-05-19 um 16 10 49" src="https://cloud.githubusercontent.com/assets/1157669/15396864/3f6d3c9c-1dde-11e6-8f2d-5f79791aa4a5.png">

Without data:
[http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/washburne-elihu-benjamin](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/washburne-elihu-benjamin)

<img width="500" alt="bildschirmfoto 2016-05-19 um 16 10 34" src="https://cloud.githubusercontent.com/assets/1157669/15396920/7106ba76-1dde-11e6-9e19-7d06f3d8cba5.png">
