### ISSUE TITLE
Improve search summary for zero results

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#230]
As seen on pages with 0 search results, such as https://history.state.gov/search?q=%22America+of+States+United%22:

> Displaying 1–0 of 0 results.

A better message would be: No results were found. Or 0 results found.

**Comment by plutonik-a** [comment]
##### Show full summary if results were found
<img width="785" alt="bildschirmfoto 2016-06-21 um 14 50 39" src="https://cloud.githubusercontent.com/assets/1157669/16230176/84737a62-37c0-11e6-8e4d-17693327c22f.png">
[http://localhost:8080/exist/apps/hsg-shell/search?q=America](http://localhost:8080/exist/apps/hsg-shell/search?q=America)

---

##### Or show a notice
<img width="901" alt="bildschirmfoto 2016-06-21 um 14 50 28" src="https://cloud.githubusercontent.com/assets/1157669/16230226/b1ba804c-37c0-11e6-899f-4b9b08827932.png">
[http://localhost:8080/exist/apps/hsg-shell/search?q=%22America+of+States+United%22](http://localhost:8080/exist/apps/hsg-shell/search?q=%22America+of+States+United%22)

**Comment by joewiz** [comment]
Looks good, thanks!
