### ISSUE TITLE
[frus] frus1981-88v03 appearing as published in 2015 and 2016 on status of series page

### ISSUE THREAD

**Issue by seckroth** [eXistSolutions/hsg-shell#234]
![screen shot 2016-05-26 at 4 14 27 pm](https://cloud.githubusercontent.com/assets/7490970/15588672/f85a5a5e-235c-11e6-959e-0f7853af3cfc.png)

**Comment by joewiz** [comment]
The page where the screenshot above appears is https://history.state.gov/historicaldocuments/status-of-the-series.

**Comment by joewiz** [comment]
The templates that generate the lists in question are `frus:volumes-published-this-year` and `frus:volumes-published-last-year` from https://github.com/eXistSolutions/hsg-shell/blob/master/pages/historicaldocuments/status-of-the-series.html#L24-L27. The corresponding functions are in https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-html.xqm#L419-L445.
