### ISSUE TITLE
[frus] Overflowing images

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#241]
Images such as the ones shown on the following pages are overflowing the size of the parent div. Would it be possible to limit the maximum width of images to the size of the parent div?

The first screenshot comes from https://history.state.gov/historicaldocuments/frus1977-80v28/d6, and the second comes from https://history.state.gov/historicaldocuments/frus-history/appendix-a.

> ![screen shot 2016-06-30 at 9 41 46 am](https://cloud.githubusercontent.com/assets/59118/16490279/f2404768-3ea6-11e6-9a49-b36c4822d4c9.png)

> ![screen shot 2016-06-30 at 9 43 19 am](https://cloud.githubusercontent.com/assets/59118/16490311/1d5cc94e-3ea7-11e6-86c3-850625242d79.png)

**Comment by plutonik-a** [comment]
<img width="643" alt="bildschirmfoto 2016-08-04 um 15 45 16" src="https://cloud.githubusercontent.com/assets/1157669/17404706/ff71ef32-5a5c-11e6-988c-c3ee12d26391.png">

**Comment by joewiz** [comment]
Thank you!
