### ISSUE TITLE
Right sidebars floating leftward

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#242]
In the screenshot below notice how the Persons and Terms sidebars are floating to the left, whereas they should be directly beneath the TOC sidebar. See https://history.state.gov/historicaldocuments/frus1969-76ve05p1/d218 or http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76ve05p1/d218.

> ![screen shot 2016-07-15 at 11 32 41 am](https://cloud.githubusercontent.com/assets/59118/16879735/e76cb508-4a7f-11e6-8762-bcf5a1c1af6d.png)

**Comment by plutonik-a** [comment]
### Template Volume Interior
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76ve05p1/d218](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76ve05p1/d218)

<img width="722" alt="bildschirmfoto 2016-08-11 um 13 16 08" src="https://cloud.githubusercontent.com/assets/1157669/17587406/7434cfe0-5fc8-11e6-9690-31bb6fafcb7e.png">

### Template Frus-History
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history)

<img width="483" alt="bildschirmfoto 2016-08-11 um 13 48 16" src="https://cloud.githubusercontent.com/assets/1157669/17587974/ffe0c226-5fcb-11e6-9e3e-c2dde4e7cacd.png">

---

### Template Conferences
[http://localhost:8080/exist/apps/hsg-shell/conferences/2006-china-cold-war](http://localhost:8080/exist/apps/hsg-shell/conferences/2006-china-cold-war)

<img width="480" alt="bildschirmfoto 2016-08-11 um 14 02 00" src="https://cloud.githubusercontent.com/assets/1157669/17588016/3efeda56-5fcc-11e6-81d0-855682df554c.png">

---

### Templates with "Standalone" TOC-Sidebar
I.e. in page:
* [http://localhost:8080/exist/apps/hsg-shell/about/faq/where-are-state-records](http://localhost:8080/exist/apps/hsg-shell/about/faq/where-are-state-records)
* [http://localhost:8080/exist/apps/hsg-shell/about/hac](http://localhost:8080/exist/apps/hsg-shell/about/hac)
* [http://localhost:8080/exist/apps/hsg-shell/departmenthistory/buildings/foreword](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/buildings/foreword)
* [http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/diplomacy](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/diplomacy)
* [http://localhost:8080/exist/apps/hsg-shell/milestones/1784-1800/citizen-genet](http://localhost:8080/exist/apps/hsg-shell/milestones/1784-1800/citizen-genet)
* [http://localhost:8080/exist/apps/hsg-shell/conferences/2011-foreign-economic-policy/overview](http://localhost:8080/exist/apps/hsg-shell/conferences/2011-foreign-economic-policy/overview)
* [http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/foundations](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/foundations)
* [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/chapter-4](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/chapter-4)

**Comment by joewiz** [comment]
@plutonik-a Great, thank you for the fix - and for the illustrations and survey of affected templates.
