### ISSUE TITLE
load testing

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/hsg-shell#25]
implement load tests to ensure stability and quality of service. These have the highest priority to improve the overall experience.

Functional tests will be handled separately.

**Comment by JoernT** [comment]
@joewiz would you please create a milstone 'load testing 1' in https://github.com/joewiz/hsg-test/issues ?

**Comment by joewiz** [comment]
@joernt on the train... I made you a collaborator on hsg-test - please go ahead.

**Comment by zwobit** [comment]
created a milestone

**Comment by wolfgangmm** [comment]
I added basic load tests for content pages including ajax requests and optimised the code accordingly to remove bottlenecks. Next step would be to create more extensive tests covering a larger number of different resources.

**Comment by wolfgangmm** [comment]
Closing this in favour of more detailed tickets.
