### ISSUE TITLE
fix odd merge problems with namespaces

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/hsg-shell#29]

**Comment by tuurma** [comment]
we actually don't need that for launch, it works perfectly well with namespace added statically, it is more a general issue for tei simple

**Comment by JoernT** [comment]
@joewiz due to what Magdalena says can we just take that out of the milestone?

**Comment by joewiz** [comment]
@joernt Sure, that makes sense.

**Comment by JoernT** [comment]
sorry for confusion - hit the milestone unintentionally

**Comment by joewiz** [comment]
No worries! I didn't realize that milestones stick with issues even after they're closed. This makes sense though.
