### ISSUE TITLE
refine responsive layout and CSS of the site

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/hsg-shell#31]

**Comment by joewiz** [comment]
Some issues I see in the current design (using Chrome dev tools > iPhone 6):

- Extra whitespace above the logo. Might look better and reveal more content without this whitespace.
- The phrase "menu" appears beside the hamburger icon. I think the icon suffices.

> ![localhost_8080_exist_apps_hsg-shell_](https://cloud.githubusercontent.com/assets/59118/11342025/33ffa86e-91d3-11e5-88e0-e2d11005423d.png)

- When viewing the menu, the white text on light background is hard to read.

> ![localhost_8080_exist_apps_hsg-shell_](https://cloud.githubusercontent.com/assets/59118/11342116/a88e0f68-91d3-11e5-8180-45da2c3c1416.png)

- Not a mobile-specific issue here, but there is a lot of whitespace above the `<h1>` element:

> ![office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/11342367/08d289f2-91d5-11e5-912e-49938dde4a40.png)

Should we apply the old site's red, all-caps styling from `<h2>` to the new site's `<h1>`? The current `<h1>` feels too high, large.  

> ![the_historian_-_about_us_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/11342405/4f093a10-91d5-11e5-829f-18d4b86387a5.png)

These are just things I've been noticing. How we approach them depends on when we fold in the USWDS project.

**Comment by JoernT** [comment]
# First mockup for about.html

original page from repo on 7th Dec.
![about0](https://cloud.githubusercontent.com/assets/484059/11630999/4cdef474-9d00-11e5-8f2b-f78fc4ddf951.png)

## 1. draft
concentrates on fonts and typesetting.

What has been done:
* Using merriweather and source sans pro as fonts (adapted from USWDS)
* adapted typesetting to USWDS
* reworked side panel
* optimized space between breadcrumb and content
* inherit breadcrumb size from default font-size
* using navbar background color as link color
* navbar background now uses the blue from the logo text

![about1](https://cloud.githubusercontent.com/assets/484059/11631317/b5479970-9d01-11e5-94a9-c4f475f40eba.png)

**Comment by JoernT** [comment]
Btw, shouldn't the panel be titled 'Related' instead of 'About'?

**Comment by JoernT** [comment]
latest local version with refinements and changed panel styling

![about2](https://cloud.githubusercontent.com/assets/484059/11633681/e1c1bb06-9d0c-11e5-9153-22392e1fb1aa.png)

**Comment by JoernT** [comment]
![about3](https://cloud.githubusercontent.com/assets/484059/11634155/3d7a0b90-9d0f-11e5-978e-5a48c67f7ee4.png)

**Comment by joewiz** [comment]
@JoernT I really like the drafts you've created here - and can see how you addressed each of the items in your list above.  The breadcrumb size and link color/nav bar background is great, and I like the sidebar shadow/ border contrast and the footer spacing.  I think this is a good foundation here.  Just a couple of requests:

Could you show how this would look with Meriweather as the body font, as in the USWDS typography example labeled "Merriweather headings and body" at https://playbook.cio.gov/designstandards/visual-style/?  The description for that example perfectly matches the tone we're looking for.

Does the spacing between paragraphs seem a little tight to you?  I think a little more spacing would help paragraphs - particularly the short ones - appear more distinct.

When you prepare the sample page on a FRUS document, I will be interested in how you approach the sidebar.  It would be nice to have a unified sidebar style across sections.  See the current form (taken from https://history.state.gov/beta/historicaldocuments/frus1955-57v22/d1):

> ![screen shot 2015-12-07 at 1 45 13 pm](https://cloud.githubusercontent.com/assets/59118/11636227/08f95540-9ce9-11e5-9dc5-c0994c7d7fed.png)

**Comment by joewiz** [comment]
Oh, and as to the question of the sidebar's heading, I agree that "About" is odd here and should be changed.  On the old site, these left sidebars often were lists of links in the section.  Since this section is the "About" section, that was the title of the sidebar.  I'll play with a few alternatives and will make the change.

**Comment by JoernT** [comment]
what a pitty that github doesn't support nested commenting....

* as for the asides - of course we will apply a consisting look across the site.
* i'll try applying Merriweather - however i like the contrast between headings and text - the vice versa would also be interesting to look at (Source Sans for the headings and Merriweather for the text)
* Most important to look at IMO is the text width - i'll show you the difference live - the readability of the text is not good at the moment as it runs much too broad.

**Comment by JoernT** [comment]
page with Merriweather as body font - 
![about4](https://cloud.githubusercontent.com/assets/484059/11783567/41ebd73a-a278-11e5-9921-4b9bc55d5e86.png)

For my taste this makes the overall look a bit boring again - the contrast of the fonts makes the page more interesting IMO.

**Comment by JoernT** [comment]
here's the contrary - source sans for the headings and Merriweather for the paragraphs

![about5](https://cloud.githubusercontent.com/assets/484059/11783688/c817af78-a278-11e5-83fa-dfc2bb318b12.png)

**Comment by joewiz** [comment]
@JoernT Can you please check the previous 2 images? In the first image the heading and body font both look more like Georgia than Merriweather; in the second image, the body font also looks like Georgia. 

From your image:

> <img width="870" alt="screen shot 2015-12-14 at 10 36 05 am" src="https://cloud.githubusercontent.com/assets/59118/11785182/85d0f450-a24e-11e5-92d8-651a16afe146.png">

My sense of what Merriweather would look like in this paragraph:

> <img width="855" alt="screen shot 2015-12-14 at 10 37 31 am" src="https://cloud.githubusercontent.com/assets/59118/11785223/b7541dd6-a24e-11e5-9171-41769af319f5.png">

Also, note that based on the code currently in the repo, http://localhost:8080/exist/apps/hsg-shell/design/about.html is not loading either custom font. But view-source:http://localhost:8080/exist/apps/hsg-shell/design/about-merriweather.html is loading both Merriweather and Source Sans Pro.

**Comment by JoernT** [comment]
addressed these areas:

* fonts changed to Merriweather and Source Sans Pro
* the text column now is more narrow to improve readability of the texts. This is done just by CSS without any changes to the HTML markup.
* appropriate media queries have been added to remove paddings for smaller devices
* the right-side panels have been unified and use lists without bullet and paddings
* general list styles now use more space at the bottom

The rough rework should be done - detail issues that pop up should be handled in seperate tickets.

One area would be editing the pages for consistent use of heading elements. This would improve the overall consistency.
