### ISSUE TITLE
extend ajax module to other publications

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#34]
As noted in https://github.com/eXistSolutions/hsg-shell/commit/a8e70d6e3739a8766baa798cd8bf1a434092e38c, frus-ajax.xql makes FRUS-specific assumptions about URLs passed to it. It breaks when applied to other publications with different URL patterns.  Specifically:

- currently the frus-ajax.xql library parses the url parameter passed to it to divine the publication, document, and section IDs needed for calling pages:load-xml.
- this worked for FRUS, where links were `/publication/document/section`, but not in sections of the site like the FAQ, e.g., `/about/faq`, where `faq` is the publication ID and `about` is irrelevant to loading the XML
- thus, URL parsing is inadequate.
- solution: either generate per-publication ajax libraries, or pass the ajax library the publication ID so it can lookup the proper select-document or select-section function from $config:PUBLICATIONS.
- TODO: @wolfgangmm please investigate whether we could somehow modify app.js to pass the publication-id to frus-ajax.xql. this is beyond my javascript abilities
- TODO: please test a solution against FRUS and the about/faq example mentioned above - ensuring TOC links work. this commit leaves the about/faq ajax links broken (though loading each page works)

**Comment by wolfgangmm** [comment]
I committed a preliminary fix in 26e3004b3e5cc5ee165995eced549ace4b3853bf. Unless there will be a lot of other cases to be handled, it might be sufficient, so I'm closing the issue for now.

**Comment by joewiz** [comment]
Interesting. I will keep thinking about this, but will try to use this workaround in the meantime. It feels like the start of a generalized content API endpoint, which if fleshed out could offer some interesting capabilities.
