### ISSUE TITLE
templates:each problem on homepage

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#37]
After adding a twitter section to index.html, I noticed what appears to be an extra bullet point in the output of this section:

> <img width="356" alt="screen shot 2015-11-29 at 6 58 53 pm" src="https://cloud.githubusercontent.com/assets/59118/11461138/44973b40-96cb-11e5-9296-67473b9cf0dd.png">

The underlying markup shows that the 3 desired list items are actually surrounded by an extra `<li data-template="templates:each">` element:

```
<ul data-template="app:load-most-recent-tweets">
    <li data-template="templates:each" data-template-from="tweets" data-template-to="tweet">
        <li data-template="templates:each" data-template-from="tweets" data-template-to="tweet"
            >Experience in the Navy’s nuclear sub program influenced Carter’s position on safeguards
            and the nuclear fuel cycle. <a href="http://go.usa.gov/caK64">go.usa.gov/caK64</a>
            <ul>
                <li><a href=""><span data-template="app:tweet-href"
                            href="https://twitter.com/HistoryAtState/status/667795331900403712"/>20
                        Nov</a>
                </li>
            </ul>
        </li>
        <li data-template="templates:each" data-template-from="tweets" data-template-to="tweet"
            >Interested in the Treaty of Tlatelolco and the nuclear free zone in Latin America? <a
                href="http://go.usa.gov/caK64">go.usa.gov/caK64</a>&#160;<a
                href="https://twitter.com/search?q=%23FRUS&amp;src=hash">#FRUS</a>&#160;<a
                href="https://twitter.com/search?q=%23twitterstorians&amp;src=hash"
                >#twitterstorians</a>
            <ul>
                <li><a href=""><span data-template="app:tweet-href"
                            href="https://twitter.com/HistoryAtState/status/668799219738812416"/>23
                        Nov</a>
                </li>
            </ul>
        </li>
        <li data-template="templates:each" data-template-from="tweets" data-template-to="tweet">The
            UN SSOD allowed the Carter administration to explore and encourage multilateral arms
            control initiatives. <a href="http://go.usa.gov/caK64">go.usa.gov/caK64</a>&#160;<a
                href="https://twitter.com/search?q=%23FRUS&amp;src=hash">#FRUS</a>
            <ul>
                <li><a href=""><span data-template="app:tweet-href"
                            href="https://twitter.com/HistoryAtState/status/668829475824672768"/>23
                        Nov</a>
                </li>
            </ul>
        </li>
    </li>
</ul>
```

I read the docs on the usage of `templates:each` at http://exist-db.org/exist/apps/demo/examples/templating/templates.html and http://exist-db.org/exist/apps/doc/templating.xml#D2.2.11.4.  I can't see what I'm missing.

**Comment by wolfgangmm** [comment]
It seems we have a fix for this issue in shared-resources already, but it has not made it into a release yet. Building shared-resources from git does help though.

Maybe I'll create a new version tomorrow. I would just like to apply some additional fixes.

**Comment by joewiz** [comment]
That's great! That same commit (https://github.com/eXist-db/shared-resources/commit/ccba1369009a97ad7b5a46884821d8a1d85b98aa) also adds something I was going to ask about - stripping the `@data-template` attributes from output. 

Sounds like a good plan!

**Comment by joewiz** [comment]
I built shared-resources from the master branch and can confirm that it fixes the extra <li> problem reported.

**Comment by joewiz** [comment]
addressed for now by checking out master branch
