### ISSUE TITLE
Broader stress tests

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#39]
The jmeter tests I already created cover the core page display as well as ajax navigation. However, they are limited to a hand full of documents.

Create more extensive tests covering a larger selection of different resources.

**Comment by joewiz** [comment]
Is there anything I can provide that would facilitate this? A list of representative pages, 1 per major view of each resource?

**Comment by wolfgangmm** [comment]
Addressed by hsg-test's creation of junit tests from jmx status reports.
