### ISSUE TITLE
Problems with `<title>` contents

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#43]
The following pages have blank `<title>` elements:

- [x] http://localhost:8080/exist/apps/hsg-shell/ (homepage)
- [x] http://localhost:8080/exist/apps/hsg-shell/about/contact-us
- [x] http://localhost:8080/exist/apps/hsg-shell/about/recent-publications
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments and all non-TEI pages under this section, e.g.:
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/truman
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/about-frus
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/status-of-the-series

The following pages' `<title>` values are incomplete and say just "Office of the Historian":
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/ebooks - should match breadcrumb hierarchy in reverse
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history and all sub-pages underneath, e.g.:
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/documents/1959-11-06-hac-meeting-minutes - compare to https://history.state.gov/historicaldocuments/frus-history/documents/1959-11-06-hac-meeting-minutes<br>
**Dev:** `Transcript of Historical Advisory Committee Meeting, November 1959 - Office of the Historian`<br>
**Live:** `Transcript of Historical Advisory Committee Meeting, November 1959 - Documents - History of the Foreign Relations Series - Historical Documents - Office of the Historian`
- [x] http://localhost:8080/exist/apps/hsg-shell/open - should start with "Open Government Initiative"

**Comment by joewiz** [comment]
another blank `<title>` element:

- [ ] http://localhost:8080/exist/apps/hsg-shell/search?q=nixon - should be "Search - Office of the Historian"...

**Comment by wolfgangmm** [comment]
Probably the code which tries to extract a dynamic title should check if there's a static one, and if yes, keep that instead of overwriting it. This would allow us to write static titles for those pages which need one.

**Comment by plutonik-a** [comment]
The title for the start page is 
"Latest News - New Publication: FRUS, 1977–1980, Volume XX, Eastern Europe
                         - New Publication: FRUS, 1977–1980, Volume XXVI, Arms Control and Nonproliferation
                         - New Publication: FRUS, 1969–1976, Volume E–16, Documents on Chile, 1969–1973
                         - Stay connected - Twitter - Tumblr - Office of the Historian"
Is this the intended wording?

**Comment by plutonik-a** [comment]
I guess, the fix for titles in `historicaldocuments/frus-history/*` has to be done here [https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-html.xqm#L315](https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-html.xqm#L315), but I vaguely understand, what is happening here.

Anyway, I have checked all titles mentioned in the checklist above and marked, which ones are working and which are not.

**Comment by line-o** [comment]
@joewiz can you provide us with a list of the expected titles?
The homepage title for example is not blank anymore. It is:
```
Latest News - Now Available: FRUS, 1981–1988, Volume XIII, Conflict in the South Atlantic,
        1981–1984
                         - Now Available: FRUS, 1969–1976, Volume E–11, Part 2, Documents on South America,
        1973–1976
                         - New Publication: FRUS, 1977–1980, Volume XX, Eastern Europe
                         - Stay connected - Twitter - Tumblr - Office of the Historian
```

**Comment by line-o** [comment]
Lets make this issue only about empty titles. And create new issues for wrong ones.
@joewiz do you agree?

**Comment by line-o** [comment]
Incorrect titles moved here: https://github.com/eXistSolutions/hsg-shell/issues/151

**Comment by joewiz** [comment]
Makes sense, @line-o. Please find the expected titles at the history.state.gov equivalent of each page. You might find these bookmarklets (tested in Chrome) useful:

**hsg-shell-dev > hsg-beta-prod (new tab)**
`javascript:(function(){window.open("https://history.state.gov/beta/"+window.location.pathname.split("/").slice(4).join("/")+window.location.search);})();`

**hsg-shell-dev > hsg-prod (new tab)**
`javascript:(function(){window.open("https://history.state.gov/"+window.location.pathname.split("/").slice(4).join("/")+window.location.search);})();`

**hsg-beta-prod > hsg-shell-dev (new tab)**
`javascript:(function(){window.open("http://localhost:8080/exist/apps/hsg-shell/"+window.location.pathname.split("/").slice(2).join("/")+window.location.search);})();`

**hsg-prod > hsg-shell-dev (new tab)**
`javascript:(function(){window.open("http://localhost:8080/exist/apps/hsg-shell/"+window.location.pathname+window.location.search);})();`

hsg-prod means history.state.gov
hsg-beta-prod means history.state.gov/beta
hsg-shell-dev means localhost:8080/exist/apps/hsg-shell

For versions that open in the same tab instead of a new tab, remove `window:open`.

**Comment by joewiz** [comment]
@line-o An alternate method of retrieving/testing titles would be to run this in eXide, providing the desired URLs in the `$urls` variable:

```xquery
xquery version "3.0";

import module namespace hc="http://expath.org/ns/http-client";

declare namespace html="http://www.w3.org/1999/xhtml";

let $urls := ('https://history.state.gov/historicaldocuments')
for $url in $urls
let $html := hc:send-request(<hc:request method="get" href="{$url}"/>)[2]
return 
    ($html//html:title, $html//title)[1]/string()
```

**Comment by line-o** [comment]
@joewiz these lines of xquery look tempting :+1:

**Comment by joewiz** [comment]
Oh good! :smile:

**Comment by line-o** [comment]
The open government initiative page can not be found on dev or beta!
https://history.state.gov/beta/open

**Comment by joewiz** [comment]
Thanks for spotting this, @line-o! I've deployed the fix (along with a fully up-to-date build of hsg-shell from the master branch) to hsg/beta.

**Comment by line-o** [comment]
While crawling both the current and the beta site it seemed useful to store both titles in a list for later comparison. 
each line represents one page (beta URL, title match, expected title, actual title)
@-signs are replaced white-space characters
[title-comparison.tsv.txt](https://github.com/eXistSolutions/hsg-shell/files/195537/title-comparison.tsv.txt)

**Comment by joewiz** [comment]
To confirm, these are the results for the non-`/historicaldocuments/frus*` pages, correct?

**Comment by line-o** [comment]
Yeah, sure.

**Comment by joewiz** [comment]
Great, this is really helpful.

**Comment by line-o** [comment]
@joe Should we open up issues for different page types?

**Comment by line-o** [comment]
https://github.com/eXistSolutions/hsg-shell/issues/173

**Comment by joewiz** [comment]
I think whitespace should be eliminated as a significant difference. The place to focus analysis of the cause of the remaining significant differences will either be:

1. The hard-coded `title` property in `$config:PUBLICATIONS` - see https://github.com/eXistSolutions/hsg-shell/blob/master/modules/config.xqm#L99. For example, the typo "Indes" should be corrected as "Index" at https://github.com/eXistSolutions/hsg-shell/blob/master/modules/config.xqm#L168.
2. **or**, if there is no `title` property, the dynamic logic which takes over  in `pages:load()` - see https://github.com/eXistSolutions/hsg-shell/blob/master/modules/pages.xqm#L58-L83 (reproduced in frus-ajax.xql's https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-ajax.xql#L87-L104)

As far as I know, these are the only two sources for `<title>` data.

@line-o Sure - or however you all would like to organize the response is fine with me.

**Comment by line-o** [comment]
Work on Titles will take place in PR #177

**Comment by plutonik-a** [comment]
I've found a strange behavior when working on page titles in [http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/worlds](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/worlds):
Refreshing the page in the browser renders a different page title than just using the prev/next arrows in the page. Strangely enough, the latter gives me the correct titles!

The page title has to consist of a dynamic title (the current headline of the div in `$content`) plus a static string written in the template.
My problem is, that with my function, I get two headings, the current one and the one of the parent category.

This is the function `pages:deep-section-page-title()`:
```
declare function pages:deep-section-page-title($node, $model) {
    if ($model?data instance of element(tei:div)) then
        for $div in $model?data/ancestor-or-self::tei:div[@xml:id]
        return $div/tei:head/string()
    else root($model?data)//tei:title[@type = 'short']/string()
};
```
I'm calling the function in the template `pages/departmenthistory/short-history/section.html` like this:
` <div id="static-title" class="hidden"><span data-template="pages:deep-section-page-title"/> - Short History - Department History</div>`

**Browser output after refreshing the page -> incorrect title:**
<img width="848" alt="bildschirmfoto 2016-04-26 um 10 53 15" src="https://cloud.githubusercontent.com/assets/1157669/14812677/740479f4-0b9e-11e6-959b-88e85400cc72.png">

**Browser output after navigating the page with prev/next -> correct title:**
<img width="844" alt="bildschirmfoto 2016-04-26 um 10 52 52" src="https://cloud.githubusercontent.com/assets/1157669/14812687/7f557434-0b9e-11e6-8062-27dd2a73994e.png">

**Question:**
Do you see any possible improvements or mistakes in my function to get just the correct output as shown in the second screenshot?

**Comment by line-o** [comment]
You could call `root($model?data)//tei:title[@type = 'short']/string()` directly. As that is the one you want to show.
You may need a new function for that.

**Comment by plutonik-a** [comment]
Problem solved: I just needed to modify the xpath expression `tei:div[@xml:id]` to `tei:div[1]` and concatenate with the category title like this:
```
declare function pages:deep-section-page-title($node, $model) {
    if ($model?data instance of element(tei:div)) then
        for $div in $model?data/ancestor-or-self::tei:div[1]
        return concat($div/tei:head/string(), ' - ', pages:section-category($node, $model))
    else ()
};

declare function pages:section-category($node, $model) {
    root($model?data)//tei:title[@type = 'short']/string()
};
```

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/issues/187
