### ISSUE TITLE
Show TOC for inner divs instead of the whole div's body content

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#44]
For example:

- http://localhost:8080/exist/apps/hsg-shell/about/faq/state-records
- http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/foundations
- http://localhost:8080/exist/apps/hsg-shell/conferences/2010-southeast-asia/background-materials (see the top level TOC: http://localhost:8080/exist/apps/hsg-shell/conferences/2010-southeast-asia)

**Comment by JoernT** [comment]
can you be more specific? Looked at the pages but couldn't find out what you're after

**Comment by wolfgangmm** [comment]
Fixed. Closing.
