### ISSUE TITLE
TOC broken link problems

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#45]
For example:

- http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history - clicking on first chapter's first subchapter link does nothing
- http://localhost:8080/exist/apps/hsg-shell/about/hac - first child of "meeting notes" chapter is "meeting notes"

**Comment by wolfgangmm** [comment]
If you go to http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history, the first link "Foundations of Foreign Affairs, 1775-1823" displays the entire chapter and pagination fails. The following links are ok.

**Comment by wolfgangmm** [comment]
Should be ok now. Closing.
