### ISSUE TITLE
prev/next nav needs to update >1 level of breadcrumbs

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#47]
Prev/next nav sometimes needs to update not only the current level of the breadcrumb hierarchy, but the parent level too.  Currently, prev/next nav is mangling these cases - producing duplicate entries. A few representative examples:

- http://localhost:8080/exist/apps/hsg-shell/about/hac/intro
    - "Authority and ResponsibilitiesAuthority and Responsibilities"
- http://localhost:8080/exist/apps/hsg-shell/conferences/2011-foreign-economic-policy/hormats
    - "Keynote Address by Under Secretary Robert HormatsKeynote Address by Under Secretary Robert Hormats"
- http://localhost:8080/exist/apps/hsg-shell/conferences/2007-detente/roundtable2
    - "Opening Remarks by Dr. Henry KissingerOpening Remarks by Dr. Henry Kissinger"

**Comment by joewiz** [comment]
I'm hoping for a systematic fix, not a local fix, that we can apply to all sections that require complex breadcrumbs.

**Comment by wolfgangmm** [comment]
Duplicate of #75
