### ISSUE TITLE
problems with conferences content

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#51]
- links in TOC don't work: http://localhost:8080/exist/apps/hsg-shell/conferences/2012-national-security-policy-salt
- see prev/next nav issue above with this same page
- http://localhost:8080/exist/apps/hsg-shell/conferences/2011-foreign-economic-policy links to "Location" and "Schedule" don't work
- TOC to inner divs has no links http://localhost:8080/exist/apps/hsg-shell/conferences/2011-foreign-economic-policy/audio-transcripts. similarly, http://localhost:8080/exist/apps/hsg-shell/conferences/2010-southeast-asia/videos-transcripts.
- see prev/next nav issue "next button goes to same page" re: http://localhost:8080/exist/apps/hsg-shell/conferences/2010-southeast-asia/program
- see "missing content" issue for conferences pages
- TOC links to "Photo Montage" and sibling divs don't work http://localhost:8080/exist/apps/hsg-shell/conferences/2010-southeast-asia

**Comment by joewiz** [comment]
Please consult the corresponding pages on the old history.state.gov site, as well as the source TEI. In general, we supply `@xml:id` attributes on all `<div>` elements that are supposed to appear in tables of contents; but on the old site I did write custom TOC code and/or make changes to TEI files to get them to work as shown on the old site. 

In researching a solution, please keep in mind cross-site consistency.

**Comment by wolfgangmm** [comment]
All the toc links mentioned should work. Closing for now. Please open new tickets if you see links which do not work yet.
