### ISSUE TITLE
add tooltip to prev/next nav

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#57]
prev & next nav buttons should be extended to display information about their targets.  should display upon first (HTML) load and upon subsequent AJAX fetches (frus-ajax.xql).  

the text may well be publication-specific, so perhaps a tooltip function is needed in the `$config:PUBLICATIONS` map?

**Comment by plutonik-a** [comment]
First attempt to fix this is made with https://github.com/eXistSolutions/hsg-shell/commit/87a08fcebb706b9df41e478a7d08ec965043e355.
At least, the links are accessible now with a simple static tooltip showing "Previous Page", "Next Page".

To dynamically replace the static `title` attribute in the links here with the related page title, we need to extend the `function pages:navigation-link` in `modules/view.xql` I think.

**Comment by plutonik-a** [comment]
When I think about it, a standard tooltip will cover the arrow, especially when the information in the tooltip contains sometimes very long chapter titles.
Maybe we should find an alternative solution to provide target information.
