### ISSUE TITLE
add custom breadcrumb code

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#60]
Pages needing custom breadcrumb entry code, like what we have in `pages/countries/article.html` (which relies on `pages:document-link`, `pages:section-link`, `pages:deep-section-breadcrumbs`, etc.:

- [x] http://localhost:8080/exist/apps/hsg-shell/education/modules/documents-intro (see pages/education/module.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/tags/seward-william-henry (see pages/tags/browse.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/part-2 (see pages/historicaldocuments/frus-history/monograph-interior.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/documents/1959-11-06-hac-meeting-minutes (see pages/historicaldocuments/frus-history/documents/document.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/production-and-timeliness-data (see pages/historicaldocuments/frus-history/research/article.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775 (see pages/milestones/chapter/index.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775/parliamentary-taxation (see pages/milestones/chapter/article.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/principalofficers/secretary-ad-interim (see pages/departmenthistory/people/principalofficers/by-role-id.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/forsyth-john (see pages/departmenthistory/people/person.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/chiefsofmission/representative-to-usoarn (see pages/departmenthistory/people/chiefsofmission/by-role-or-country-id.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/by-name/a (see pages/departmenthistory/people/by-name/letter.html)
- [x] http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/by-year/1850 (see pages/departmenthistory/people/by-year/year.html)

**Comment by plutonik-a** [comment]
I've found a weird one with missing `<li>` tags:
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v03/d1](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1945v03/d1)

````
<div class="col-md-8 col-md-offset-1">
    <ol class="breadcrumb">
        <li><a href="/exist/apps/hsg-shell">Home</a></li>
        <li><a href="/exist/apps/hsg-shell/historicaldocuments">Historical Documents</a></li>
              <a href="../frus1945v03" data-template="frus:volume-breadcrumb">Foreign Relations of the United States: Diplomatic Papers, 1945, European Advisory Commission, Austria, Germany, VolumeIII</a>
              <a href="d1" class="section-breadcrumb" data-template="frus:section-breadcrumb">Document 1</a>
      </ol>
</div>
```
