### ISSUE TITLE
Create list CSS classes to match range of uses of lists

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#64]
A suggestion from a beta tester:

> Looks like `<mission-note>` elements are getting a bullet point – they didn’t in the old design and I think it looks better without, if possible:
> 
> https://history.state.gov/beta/departmenthistory/people/chiefsofmission/afghanistan
>
> https://history.state.gov/departmenthistory/people/chiefsofmission/afghanistan

We've discussed the need for a set of sitewide list styles CSS - but I don't believe that's captured explicitly in other issues.

**Comment by JoernT** [comment]
this is fixed now

**Comment by joewiz** [comment]
For the record, here is how the page looks now:

![people_-_department_history_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/12147766/997174ae-b468-11e5-8813-44403ecab0e3.png)
