### ISSUE TITLE
List formatting

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#65]
With the new design, list formatting inside the main page content got lost. See

http://localhost:8080/exist/apps/hsg-shell/departmenthistory

<img width="463" alt="bildschirmfoto 2015-12-22 um 17 46 54" src="https://cloud.githubusercontent.com/assets/607433/11960695/2d297430-a8d4-11e5-8439-31f14c7fb534.png">

**Comment by wolfgangmm** [comment]
Also applies to the footnotes section:

![image](https://cloud.githubusercontent.com/assets/607433/11962683/f2d2e948-a8e1-11e5-9298-e1be0abe69dc.png)

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v01/d10

**Comment by joewiz** [comment]
Looks good. Current views of the previously cited entries:

* http://localhost:8080/exist/apps/hsg-shell/departmenthistory

> ![department_history_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/12148822/8c603092-b46e-11e5-9b9a-7d47c00d85b2.png)

Code for this list:

```html
<ul>
    <li>the newly independent states,</li>
    <li>the global economy,</li>
    <li>terrorism, and</li>
    <li>the security of the American overseas presence. </li>
</ul>
```

* http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v01/d10

> ![10__letter_from_president_nixon_to_secretary_of_defense_lairdsource__national_archives__nixon_presidential_materials__nsc_files__box_220__agency_files__department_of_defense__vol__i__1_12_69__secret__president_nixon_sent_an_identical_letter](https://cloud.githubusercontent.com/assets/59118/12148898/e9ff85b8-b46e-11e5-9341-bfd6198efdab.png)

Code for this list:

```html
<div class="footnotes">
    <ol>
        <li class="footnote" id="fn:1.3.2.1.16.4.5" value="1">
            <span class="fn-content">Source: National Archives, <span class="tei-persName"
                    >Nixon</span> Presidential Materials, <span class="tei-gloss">NSC</span> Files,
                Box 220, Agency Files, Department of Defense, Vol. I, 1/12/69. Secret. President
                    <span class="tei-persName">Nixon</span> sent an identical letter on February 4
                to Secretary of State <span class="tei-persName">Rogers</span>. (Ibid., Box 279,
                Agency Files, Department of State, Vol. I, 1/17/69)</span>
            <a href="#fnref:1.3.2.1.16.4.5" class="fn-back">↩</a>
        </li>
        <li class="footnote" id="fn:1.3.2.1.16.8.2" value="2">
            <span class="fn-content">In his inaugural address, <span class="tei-persName"
                    >Nixon</span> said: “We cannot learn from each other until we stop shouting at
                one another—until we speak quietly enough so that our words can be heard as well as
                our voices.” (<span class="tei-hi2">Public Papers of the Presidents of the United
                    States: <span class="tei-persName">Richard Nixon</span>, 1969</span>, p.
                2)</span>
            <a href="#fnref:1.3.2.1.16.8.2" class="fn-back">↩</a>
        </li>
    </ol>
</div>
```
