### ISSUE TITLE
Font conflicts

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#66]
Mixed fonts used in heading since spans have a different font declared:

<img width="741" alt="bildschirmfoto 2015-12-22 um 17 52 26" src="https://cloud.githubusercontent.com/assets/607433/11960813/d21c7ece-a8d4-11e5-8111-26322b0c5b59.png">

http://localhost:8080/exist/apps/hsg-shell/about/faq/what-is-frus

**Comment by joewiz** [comment]
Here's an image showing the problem:

<img width="489" alt="screen shot 2015-12-22 at 12 07 17 pm" src="https://cloud.githubusercontent.com/assets/59118/11961127/947ef0cc-a8a4-11e5-9a1e-03ee2a3a9d9b.png">

**Comment by joewiz** [comment]
The relevant markup:

```
<h2 class="head5">What is <span class="title">Foreign Relations of the United States</span>?</h2>
```

**Comment by JoernT** [comment]
besides the problem (which is easy to fix) i ask myself what this span actually adds to the statement of the header here - should there some kind of emphasis / italics or whatever?

Furthermore the markup uses an additional class of 'head5" which does not make a lot of sense to me.

**Comment by wolfgangmm** [comment]
The .head5 is added by the TEI PM library, indicating that this output was generated by the 5th alternative in the processing rules for head. We have to distinguish between the alternatives somehow because they usually need different styling despite being triggered by the same TEI element.

**Comment by JoernT** [comment]
@wolfgangmm ok - understood.

**Comment by wolfgangmm** [comment]
Still not fixed completely, see http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/kennedy

![image](https://cloud.githubusercontent.com/assets/607433/12078525/0d42f542-b216-11e5-8ddc-dac4726d1871.png)

**Comment by wolfgangmm** [comment]
Another one here:

http://localhost:8000/exist/apps/hsg-shell/historicaldocuments/frus1969-76v02/d5

![image](https://cloud.githubusercontent.com/assets/607433/12336532/4a0b8d84-bb05-11e5-8ea2-3282cce67a34.png)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/6be05f35399cc0ab0b78900a988cddf58e60ef09

Please see comment https://github.com/eXistSolutions/hsg-shell/commit/6be05f35399cc0ab0b78900a988cddf58e60ef09#commitcomment-16146461
