### ISSUE TITLE
Duplicate titles rendered

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#69]
http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/chapter-1

![image](https://cloud.githubusercontent.com/assets/607433/11961370/55ba9808-a8d8-11e5-8e82-88b8e5c82601.png)

**Comment by joewiz** [comment]
Both versions of each chapter title appear in the source TEI (https://github.com/HistoryAtState/frus-history/blob/master/monograph/frus-history.xml):

```
<div type="chapter" xml:id="chapter-1">
    <head>Chapter 1: The Parameters of Openness and Executive Discretion, 1790–1860</head>
    <head type="shortened-for-running-head">Parameters of Openness and Executive Discretion, 1790–1860</head>
```

The first `<head>` is meant for display in the text, and the other is a shortened version for use as a running header in the PDF edition.

Perhaps there is a better TEI tag for this latter use, and I'm open to suggestions from our TEI experts here.  Or a short-term fix could be to drop `<head>` elements with the `@type` here.

**Comment by tuurma** [comment]
![screenshot 78](https://cloud.githubusercontent.com/assets/449468/12140458/0f577686-b460-11e5-89ad-031d7210f8a1.png)

**Comment by joewiz** [comment]
@tuurma Thanks! I can confirm that the duplicate title is no longer shown, but I don't understand how https://github.com/eXistSolutions/hsg-shell/commit/6737f9405739cc32705f9afd4a7bebb1ca858152 fixed this. That change seemed limited to `< publicationStmt>` - but this issue related to `<head>` within `<div>`. Can you explain this?

**Comment by tuurma** [comment]
Actually 9e727ba fixes this by adding 'omit' behaviour for head/@type=''shortened-for-running-head"; forgot to mention issue # in the commit and only put that into the next one, sorry

**Comment by joewiz** [comment]
Oh, I see - and I see you referenced that commit in your commit message.
