### ISSUE TITLE
Dropdown styling on milestones entry page

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#70]
Looks somewhat ugly:

http://localhost:8080/exist/apps/hsg-shell/milestones

![image](https://cloud.githubusercontent.com/assets/607433/11962843/2796ba78-a8e3-11e5-886b-1dbe8963be9e.png)

Same issue applies to countries:

![image](https://cloud.githubusercontent.com/assets/607433/11962948/ced1d80e-a8e3-11e5-87a1-4a46b2106aa6.png)

**Comment by JoernT** [comment]
hm, strange - i already added some margin at the bottom - have to check

**Comment by JoernT** [comment]
increased margin even a bit more - make sure you got latest version and shift-reload

**Comment by joewiz** [comment]
I am not seeing a change. Using the latest version and having done a shift-reload:

* http://localhost:8080/exist/apps/hsg-shell/milestones

> ![milestones_in_the_history_of_u_s__foreign_relations_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/12149181/4792d274-b470-11e5-973e-ca64611c8c6c.png)

* http://localhost:8080/exist/apps/hsg-shell/countries

> ![countries_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/12149200/61a28740-b470-11e5-83ed-be218b24f0cd.png)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/fe97b9dddf3e6ff2e444d50620415acba504c350
