### ISSUE TITLE
Empty "Links" side box on some pages

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#71]
http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v07

![image](https://cloud.githubusercontent.com/assets/607433/11962995/33119692-a8e4-11e5-9ee0-7929f795a40d.png)

**Comment by joewiz** [comment]
Yes. Compare to http://history.state.gov/historicaldocuments/frus1969-76v07:

> <img width="144" alt="screen shot 2015-12-22 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/59118/11964342/fdfa2790-a8ba-11e5-8a83-0e023696f64a.png">

Notably:

1. Search inside this volume search box, which sends the query to http://history.state.gov/search?q=kissinger+AND+le&within=frus1969-76v07
2. Links to download the PDF and Ebooks (if available, as determined by the presence of listings of files stored on S3 - see the s3 app - https://github.com/joewiz/s3)
3. Links to Worldcat entries, as retrieved from, e.g., https://github.com/HistoryAtState/frus/blob/master/bibliography/frus1969-76v07.xml#L16 (ISBN query) or https://github.com/HistoryAtState/frus/blob/master/bibliography/frus1958-60v03mSupp.xml#L8 (WorldCat OCLC ID query)
4. Simple link to GPO: https://bookstore.gpo.gov/catalog/international-foreign-affairs/foreign-relations-united-states-series-frus
5. List of tags for this resource. Tags are defined in https://github.com/HistoryAtState/tags, and hsg-shell has a module where tags-related functions are stored, `modules/tags-html.xqm`: https://github.com/eXistSolutions/hsg-shell/blob/master/modules/tags-html.xqm. The old module, for reference, is in `paho-trunk/db/history/modules/tags.xqm`.

**Comment by joewiz** [comment]
Now that the code for ebook listings and tags is in place, this should be fairly straightforward. See the following code:

- http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/ebooks
- http://localhost:8080/exist/apps/hsg-shell/tags

Bumping up priority to indicate this definitely has to be ready at launch.

**Comment by joewiz** [comment]
@plutonik-a Re: the sidebar list of tags for each volume, some info is in my comment above (see "5. List of tags for this resource"), but here is the function I use in paho-trunk:

```xquery
declare function docs:sideright-tags($vol-id) {
    let $tags := collection('/db/cms/apps/tags/resources/frus')//link[. = concat('http://history.state.gov/historicaldocuments/', $vol-id)]/..
    return
        if ($tags) then 
            <div class="resources bordered">
                <h2>Tags</h2>
                <p><em>This volume has been tagged with the following entries from the <a href="/tags">Subject Taxonomy of the History of U.S. Foreign Relations</a>. Follow the links to find more resources on each subject:</em></p>
                <ul style="font-size:smaller">{
                    let $ids := doc('/db/cms/apps/tags/data/taxonomy.xml')//id
                    let $tag-ids := $tags//tag/@id
                    for $tag-id in $tag-ids
                    let $label := normalize-space($ids[. = $tag-id]/../label)
                    order by $tag-id
                    return
                        <li style="padding-bottom:0; text-indent:-1em; margin-left: 1em;"><a href="/tags/{$tag-id}" title="Resources tagged {$label}">{$label}</a></li>
                }</ul>
            </div> 
        else 
            ()
};
```

It would need to be adapted to hsg-shell's templating framework and collection structure.
