### ISSUE TITLE
Prettify tables

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#72]
Tables in content are currently unstyled. Add some bootstrap classes.

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76v07/d39

![image](https://cloud.githubusercontent.com/assets/607433/11994545/e9c769fe-aa40-11e5-8d68-61491f8fc288.png)

**Comment by joewiz** [comment]
Thanks, good eye, Wolfgang!  A couple of points:

In the most recent digitized volumes (1945-52), our editor @vak2ve has been applying table styles via `@rendition` values. For example, http://history.state.gov/historicaldocuments/frus1951v04p2/d447. Notice that these custom borders are being dropped at https://history.state.gov/beta/historicaldocuments/frus1951v04p2/d447.  Our top priority re: tables in TEI documents should be on restoring the rendition.  Also, please do not apply bootstrap classes en masse that will alter the appearance (e.g, default borders or row shading) of tables in FRUS.  With FRUS the concern is always about fidelity to the original printed book.  (Which the rendition values are our best tool for.)

Tables elsewhere on the site are wide open for improvement with good default table classes though!

**Comment by wolfgangmm** [comment]
See also tables in the departmenthistory section:

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/travels/secretary/seward-william-henry

![image](https://cloud.githubusercontent.com/assets/607433/12079212/30bb73ee-b231-11e5-9167-eb66a2233007.png)

**Comment by tuurma** [comment]
Extracted @joewiz's point into separate issue

**Comment by wolfgangmm** [comment]
Default bootstrap style (bordered) is applied to all tables without local renditions.
