### ISSUE TITLE
Duplicate breadcrumb links

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#75]
- some pages require multiple breadcrumb `<a>` tags, e.g. http://localhost:8080/exist/apps/hsg-shell/about/faq/where-are-employee-records. click on prev/next nav to see problems.
- similarly, http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/diplomatictradition

**Comment by joewiz** [comment]
This may be a dupe, or perhaps a clearer articulation, of #47

**Comment by wolfgangmm** [comment]
I split #47 into two issues. Each ticket should describe one problem only. Information contained in comments might get lost if a ticket is closed automatically from a commit.

**Comment by joewiz** [comment]
I see what you mean about #46 - apologies for letting an unrelated issue creep into the first comment - but I think #47 describes the same phenomenon as you're describing here.  If you agree, then feel free to close #47, or this one - as you wish.
