### ISSUE TITLE
Document title formatting

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#76]
Compare new:

![image](https://cloud.githubusercontent.com/assets/607433/12078069/564dba5a-b203-11e5-8aa6-714fc3075abb.png)

to old:

![image](https://cloud.githubusercontent.com/assets/607433/12078070/60bc3408-b203-11e5-9772-25df3d7aa276.png)

http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1947v07/d328

**Comment by plutonik-a** [comment]
Why are the round brackets in the headline left with `font-style: normal` when the rest of it is `italic`?
This was already the case on the old website.

**Comment by plutonik-a** [comment]
I also see a missing paragraph in the new markup, as you can see in the screenshots above.

Old site: `<p style="font-size: smaller">[Document 328]</p>`
https://history.state.gov/historicaldocuments/frus1947v07/d328

Is this intentional?

**Comment by plutonik-a** [comment]
Question: 
Where do the inline styles for the document above (http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1947v07/d328) com from?
I need to fix them, because they are causing a layout bug, but am not sure, whether editing within the markup is the right way, or if the styles are generated elsewhere.

**Comment by plutonik-a** [comment]
The markup for the headings from old and new site differ: 
old heading: h3 (12.8px)
new heading: h2 (34px)
Was the markup change for the heading intentional?

**Comment by plutonik-a** [comment]
I fixed the font-family issue with https://github.com/eXistSolutions/hsg-shell/commit/e4903c85bb363fe5689b66420a2d6bddc9f3ec9c.
But I'll leave this issue open due to my questions above.
