### ISSUE TITLE
Formatting of doc header and intro

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#77]
New: http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history

![image](https://cloud.githubusercontent.com/assets/607433/12078495/b12d6360-b214-11e5-8de7-089685037356.png)

Old:

![image](https://cloud.githubusercontent.com/assets/607433/12078496/c11d8f98-b214-11e5-9011-cefced4f3765.png)

Also compare: https://history.state.gov/historicaldocuments/frus1969-76ve11p1

![image](https://cloud.githubusercontent.com/assets/607433/12078508/2e3f9d14-b215-11e5-99c4-2ca9979fdcb9.png)

with https://history.state.gov/historicaldocuments/frus1969-76ve11p1

![image](https://cloud.githubusercontent.com/assets/607433/12078510/3e1a5d64-b215-11e5-8a98-415a5b399448.png)

**Comment by JoernT** [comment]
Sorry, but ticket does not say what the problem / intented goal is.

**Comment by wolfgangmm** [comment]
The document header needs some formatting/styling: e.g. for the intro block or list of editors. If in doubt, compare the old and new site. I don't think we should just reproduce the look of the old site, but the new one clearly lacks some elements/styling in many places. In general I'm not happy with styling and readability yet.

Note: some changes will have to be done in the tei odd to output the correct classes, but I don't think this is required for this particular issue.

**Comment by tuurma** [comment]
Hey @joewiz I noticed that in volumes editors are explicitly recorded inside titleStmt, while in  http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history one has to rely on names inside titlePage which do not provide distinction between editorial roles.

**Comment by tuurma** [comment]
Closing this for now, feel free to add more specific requests for formatting/styling.

**Comment by tuurma** [comment]
![screenshot 77](https://cloud.githubusercontent.com/assets/449468/12140429/cfaf4d42-b45f-11e5-9dd7-1f40a2976ba5.png)

**Comment by joewiz** [comment]
@tuurma This looks great! Thanks. You're also right to point out the differences in how editors/authors are handled in this frus-history monograph (where the people named are all authors) vs. frus volumes (where the people named are editors). Thus, I think the issues remaining here are:

1. Remove "Editors" label / designation from frus-history landing page. I think they should be flush left list items with no bullets/indentation, with normal line height, and with no extra padding between the items.
2. Remove excessive spacing between editors' names from frus volume landing pages:

> ![historical_documents_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/12149467/dff3ec0a-b471-11e5-9b85-a5ef7fac1340.png)

**Comment by tuurma** [comment]
Here's the look of the frus-history landing page (addresses @joewiz's 1st point above) 
![screenshot 80](https://cloud.githubusercontent.com/assets/449468/12168863/0a798fb4-b52d-11e5-8e08-28890ae8e20a.png)

**Comment by tuurma** [comment]
extracted 2nd point into separate issue, as it's to do with tei-pm and closing this one
