### ISSUE TITLE
Ebooks page

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#78]
The new page lists only two ebooks: http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/ebooks

![image](https://cloud.githubusercontent.com/assets/607433/12078519/af74343a-b215-11e5-953f-16ed0ad4f0d2.png)

Compare with https://history.state.gov/historicaldocuments/ebooks

**Comment by joewiz** [comment]
Correct. These resources needed for this page (and used elsewhere, e.g., volume landing pages) must be fetched from S3, so this issue is dependent on implementing a method for secrets (#54). As the S3 app is currently designed (see https://github.com/joewiz/s3), the credentials must be placed in `modules/aws_config.xqm`. Once the credentials are available to the app, running `cache-all.xq` will fetch all necessary resources from S3.

**Comment by joewiz** [comment]
As a temporary workaround for this until #54 is addressed, run `ant update` on hsg-shell to pull in https://github.com/joewiz/s3/commit/d4ee6a459571c3198627ce65413ccd350991c6cc, then run http://localhost:8080/exist/apps/s3/load-cache-from-zip.xq as dba. This loads a snapshot of select s3 resources from Dec 6 into the database. That zip file is obviously not a sufficient workaround for the launch, but we could close this if you feel this addresses the issue you reported.

**Comment by dizzzz** [comment]
'https://history.state.gov/historicaldocuments/ebooks' yields into a trace...

```xml
<exception>
<path>/db/history/services/volume-images.xq</path>
<message>
err:XPST0081 error found while loading module bucket: Error while loading module /db/cms/apps/aws/modules/xaws/modules/uk/co/xquery/www/modules/connectors/aws-exist/s3/bucket.xq: error found while loading module aws-request: Error while loading module ../helpers/request.xq: No namespace defined for prefix http [at line 40, column 81]
</message>
</exception>
```

**Comment by joewiz** [comment]
Thanks for spotting this @dizzzz! Please always email me directly (with all caps and exclamation marks) about any errors you get on the public site so I can take care of these right away.

**Comment by plutonik-a** [comment]
Seems to be fixed. The layout has also been fixed.
**Although I still see a bug:
The counter counts only 1 volume, but 2 are displayed!**
<img width="652" alt="bildschirmfoto 2016-03-30 um 18 56 15" src="https://cloud.githubusercontent.com/assets/1157669/14150549/d81c5b50-f6a9-11e5-9f32-1ce92bd6b8f6.png">
