### ISSUE TITLE
Table of contents: indentation of subsections

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#79]
Compare http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history

![image](https://cloud.githubusercontent.com/assets/607433/12078532/5ba593fc-b216-11e5-90bf-aae6fe2e5f3f.png)

with https://history.state.gov/historicaldocuments/frus-history

![image](https://cloud.githubusercontent.com/assets/607433/12078535/6b24ea4e-b216-11e5-9a4f-5e8fca139d46.png)

**Comment by joewiz** [comment]
For the record:

> ![office_of_the_historian](https://cloud.githubusercontent.com/assets/59118/12149605/833d9e06-b472-11e5-8d9c-9bc26814ea8f.png)

Indentation looks good. Thanks, @wolfgangmm.
