### ISSUE TITLE
Lists formatting

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#80]
http://localhost:8080/exist/apps/hsg-shell/departmenthistory

![image](https://cloud.githubusercontent.com/assets/607433/12078545/c1d27ece-b216-11e5-8432-ca24d43acc3d.png)

https://history.state.gov/departmenthistory

![image](https://cloud.githubusercontent.com/assets/607433/12078547/ce8fb58c-b216-11e5-9376-1270b3ffcd35.png)

**Comment by joewiz** [comment]
Final image can be seen in the resolution on #65 - a dupe, it appears, for what was noted here.
