### ISSUE TITLE
Images display and alignment

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#81]
Compare https://history.state.gov/departmenthistory/short-history

![image](https://cloud.githubusercontent.com/assets/607433/12078565/6373c670-b217-11e5-962d-02a539c58d90.png)

with http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/foundations

![image](https://cloud.githubusercontent.com/assets/607433/12078567/7717ed3c-b217-11e5-9be6-59a4ceefdc4f.png)

**Comment by wolfgangmm** [comment]
Found one remaining issue http://localhost:8080/exist/apps/hsg-shell/milestones/1784-1800/loans

![image](https://cloud.githubusercontent.com/assets/607433/12112211/6ae4e738-b39b-11e5-9e95-505bab09877e.png)

**Comment by plutonik-a** [comment]
@wolfgangmm 
The issue described above seems to be fixed, at least I'm not able to reproduce it.

@joewiz 
To me it seems, that the content to be fixed here, is currently missing:
http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/foundations
also on https://history.state.gov/beta/departmenthistory/short-history
