### ISSUE TITLE
People biographies missing

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#82]
Shows the biography of Jefferson: https://history.state.gov/departmenthistory/people/jefferson-thomas

![image](https://cloud.githubusercontent.com/assets/607433/12078644/53dd9012-b21a-11e5-8358-479ff8c9e886.png)

Here it is missing: http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/jefferson-thomas

![image](https://cloud.githubusercontent.com/assets/607433/12078646/73647950-b21a-11e5-970a-5ee000bf58d2.png)

**Comment by tuurma** [comment]
@joewiz any ideas where I could find the data for bio articles? in pocom/people there are only basic data on birth, career, etc. There probably was something in '/db/cms/apps/tei-content/data/secretary-bios/' but where is it now?

**Comment by joewiz** [comment]
@tuurma You're absolutely right. I've just posted the TEI files in the `other-publications` app - which you can fetch when you next run `ant update` from `hsg-project`. The repo URL is https://github.com/HistoryAtState/other-publications/tree/master/secretary-bios.

**Comment by tuurma** [comment]
Thanks @joewiz!

**Comment by wolfgangmm** [comment]
Biographies are there now.
