### ISSUE TITLE
Alphabetic listing of names

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#83]
https://history.state.gov/departmenthistory/people/by-name

![image](https://cloud.githubusercontent.com/assets/607433/12078841/e04f3fd0-b221-11e5-9e39-92f5b953ce02.png)

http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/by-name

![image](https://cloud.githubusercontent.com/assets/607433/12078850/ff34deb4-b221-11e5-96f4-37b324e40c89.png)

**Comment by JoernT** [comment]
close? Fix has been merged i guess

**Comment by wolfgangmm** [comment]
Changed to

![principal_officers_and_chiefs_of_mission_alphabetical_listing_-_department_history_-_office_of_the_historian](https://cloud.githubusercontent.com/assets/1700062/12100806/952a9872-b331-11e5-9382-bdcd09a22d54.gif)

**Comment by joewiz** [comment]
Looks good, thanks @dizzzz!

**Comment by dizzzz** [comment]
Thnx good to hear :)
