### ISSUE TITLE
Formatting of quotes

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#85]
Quotes have no proper formatting yet: http://localhost:8080/exist/apps/hsg-shell/departmenthistory/short-history/articles

![image](https://cloud.githubusercontent.com/assets/607433/12080942/9792c75e-b26b-11e5-9110-fd392015394a.png)

**Comment by SabineDM** [comment]
![screenshot 2016-01-05 15 09 49](https://cloud.githubusercontent.com/assets/1408331/12117081/854f9122-b3be-11e5-847b-0940fc727ef9.png)

further changes for quotes within the text done:

![screenshot 2016-01-05 15 12 38](https://cloud.githubusercontent.com/assets/1408331/12117137/db1f236a-b3be-11e5-823f-caf7fd0a7c14.png)

**Comment by joewiz** [comment]
This looks great. Thanks @wolfgangmm @tuurma and @SabineDM!
