### ISSUE TITLE
preserving @rendition from tei tables

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/hsg-shell#90]
Splitting from #72 
'In the most recent digitized volumes (1945-52), our editor @vak2ve has been applying table styles via @rendition values. For example, http://history.state.gov/historicaldocuments/frus1951v04p2/d447. Notice that these custom borders are being dropped at https://history.state.gov/beta/historicaldocuments/frus1951v04p2/d447. Our top priority re: tables in TEI documents should be on restoring the rendition. Also, please do not apply bootstrap classes en masse that will alter the appearance (e.g, default borders or row shading) of tables in FRUS. With FRUS the concern is always about fidelity to the original printed book. (Which the rendition values are our best tool for.)'

**Comment by wolfgangmm** [comment]
Issue should be fixed via https://github.com/wolfgangmm/tei-simple-pm/commit/f305bc294da7cc75fe5a8833985bede23ecbb3c8

Extended bootstrap classes need to be removed for the changes to become visible though.

**Comment by joewiz** [comment]
Using latest code and having run modules/rebuild.xql, I am not seeing the rendition CSS.  Using the example URLs from above: 

* http://history.state.gov/historicaldocuments/frus1951v04p2/d447

> <img width="532" alt="document_447_-_foreign_relations_of_the_united_states__1951__europe__political_and_economic_developments__volume_iv__part_2_-_historical_documents_-_office_of_the_historian" src="https://cloud.githubusercontent.com/assets/59118/12203988/a28c9f80-b5ff-11e5-8d2b-ff1689a21184.png">

* http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1951v04p2/d447 (or https://history.state.gov/beta/historicaldocuments/frus1951v04p2/d447)

> <img width="509" alt="paper_prepared_by_the_economic_cooperation_administrationaccording_to_the_cover_sheet_attached_to_the_source_text__this_eca_paper_was_circulated_as_isac_d 10_2__also_attached_to_the_source_text_was_a_memorandum_by_halaby_to_cabot__dated_jul" src="https://cloud.githubusercontent.com/assets/59118/12204031/e79b2678-b5ff-11e5-9168-cd3312aa0d6f.png">

(Note here too that the header "Funds Obligated" in the original table is missing from the hsg-shell version.)

**Comment by joewiz** [comment]
After deploying ef6765d to the beta site I'm getting a cardinality error on the document we've been using as an example - https://history.state.gov/beta/historicaldocuments/frus1951v04p2/d447:

```
exerr:ERROR XPTY0004: The actual cardinality for parameter 2 does not match the cardinality declared in the function's signature: css:get-rendition($node as node()*, $class as xs:string) item()*. Expected cardinality: exactly one, got 2. [at line 479, column 44, source: /db/apps/hsg-shell/resources/odd/compiled/frus-web.xql]
In function:
	css:get-rendition(node()*, xs:string) [479:44:/db/apps/tei-simple/content/css.xql]
	pmf:table(map, element(), xs:string+, item()*) [479:21:/db/apps/tei-simple/content/html-functions.xql]
```

**Comment by joewiz** [comment]
Ah, just noticed https://github.com/wolfgangmm/tei-simple-pm/commit/43bf2cab979e49a38886324c5e6d2a592bdc1911. Updating tei-simple-pm and redeploying it fixes the cardinality error.

**Comment by wolfgangmm** [comment]
Looks ok on a fresh build. Closing.

**Comment by joewiz** [comment]
For the record, here is a screenshot of the look of tables at the conclusion of this issue, plus a change in my commit https://github.com/eXistSolutions/hsg-shell/commit/59986967eb423fb13ca83900b199b87ea7a3b623:

> ![paper_prepared_by_the_economic_cooperation_administrationaccording_to_the_cover_sheet_attached_to_the_source_text__this_eca_paper_was_circulated_as_isac_d 10_2__also_attached_to_the_source_text_was_a_memorandum_by_halaby_to_cabot__dated_jul](https://cloud.githubusercontent.com/assets/59118/12246158/de0ad8ce-b87a-11e5-8161-5596e93adc7d.png)

(Note: the slight jaggedness in the vertical border is due to the use of `display: block` in the `#center` rendition in the source TEI file; this CSS is correctly being passed into the app.)
