### ISSUE TITLE
Missing list/head text

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#93]
Participants and subject lists are missing their headings and are not indented. 

Compare https://history.state.gov/historicaldocuments/frus1977-80v08/d1 

> <img width="533" alt="document_1_-_foreign_relations_of_the_united_states__1977 1980__volume_viii__arab-israeli_dispute__january_1977 august_1978_-_historical_documents_-_office_of_the_historian" src="https://cloud.githubusercontent.com/assets/59118/12181435/218cd3e6-b550-11e5-9565-52b43f7d4558.png">

to https://history.state.gov/beta/historicaldocuments/frus1977-80v08/d1

> <img width="775" alt="arab-israeli_dispute__january_1977 _august_1978_-_historical_documents_-_office_of_the_historian" src="https://cloud.githubusercontent.com/assets/59118/12181411/f5af749a-b54f-11e5-8560-9ae63d0554a2.png">

Notice how the text "TO", "FROM", and "SUBJECT" are missing, and the lists are not indented.  

Compare also to the print edition at https://history.state.gov/historicaldocuments/frus1977-80v08/pg_1:

> <img width="402" alt="0028_png__533x800_" src="https://cloud.githubusercontent.com/assets/59118/12181480/75cfde12-b550-11e5-9d2d-d9ff78eea8fe.png">

**Comment by joewiz** [comment]
Raised priority on this because this is leading to incomplete / confusing views on the beta site.  For example, this tweet https://twitter.com/jamesgramwilson/status/687077117788557314 links to https://history.state.gov/beta/historicaldocuments/frus1969-76v39/d324, which is missing the same participants lists and subject headings as described in this issue.  Compare to https://history.state.gov/historicaldocuments/frus1969-76v39/d324.

**Comment by wolfgangmm** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/607433/12350977/bae7b65c-bb7a-11e5-9922-c58043a392b9.png)

**Comment by joewiz** [comment]
That's looking very nice. Thank you, @wolfgangmm! I've pushed this to the beta site.
