### ISSUE TITLE
Complete /search

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#95]
The UI for the search section is complete, but the actual search queries are currently limited to the "historical documents" (FRUS) material. The search module needs to be extended to include all data collections (here I list each checkbox in the search form and the corresponding apps that have to be included):

- [x] Historical Documents: frus
- [ ] Department History: pocom, travels, visits, other-publications/short-history, other-publications/secretary-bios, other-publications/buildings, other-publications/views-from-the-embassy
- [x] Milestones: milestones
- [x] Countries: rdcr, wwdai
- [x] Conferences: conferences
- [x] Educational Resources: other-publications/education
- [x] History of the Foreign Relations Series: frus-history
- [x] About (FAQ, Advisory Committee Minutes): other-publications/faq, hac

Work on this is currently in `modules/search.xqm`, and the old code is in `/db/history/modules/search.xqm` - also uploaded here if you don't have access to the SVN repository on assembla: 
[search.xqm.zip](https://github.com/eXistSolutions/hsg-shell/files/83053/search.xqm.zip). Please follow the patterns already created for searching the frus collection. 

There are certainly opportunities for improvement here, but while I'm open to proposals and ideas, my priority is on achieving parity with the current site.

**Comment by wolfgangmm** [comment]
Still to be addressed after 3990595be8bf0a80cf91c7e131ea1d817f9c7a84:

* countries: there's no collection.xconf
* tei:div in countries do not have an xml:id

**Comment by wolfgangmm** [comment]
Search should be nearly complete now. Just missing the views-from-the-embassy and @plutonik-a will look into some styling improvements.

**Comment by plutonik-a** [comment]
@wolfgangmm 
What is the status of this issue?
The mentioned style improvements have been long done by me.
Last layout change was fixed with https://github.com/eXistSolutions/hsg-shell/commit/865c455fdb1c090aa1261c87ec3567501306c607

**Comment by wolfgangmm** [comment]
We would need to check if the "views from the embassy" document is now available. If yes, we should add it to search. Otherwise the ticket can be closed.

**Comment by joewiz** [comment]
While we only provide a link to the PDF of "views from the embassy," the text of the document is available in XML, so this could be included in the search results, with the link to the publication's landing page where the PDF appears. 

The XML is in [/db/apps/other-publications/views-from-the-embassy/views-from-the-embassy.xml](https://github.com/HistoryAtState/other-publications/tree/master/views-from-the-embassy).

The landing page for the publication, which could be used as the target for search hits, is: https://history.state.gov/departmenthistory/wwi.
