### ISSUE TITLE
Adapt /open feeds (open government data)

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#96]
history.state.gov has an atom feed for the latest 10 FRUS volumes: 

- https://history.state.gov/open/frus-latest.xml

I've already adapted the landing page for this resource: 

- https://history.state.gov/beta/open/frus-latest

history.state.gov also exposes the "bibliographic" data for all FRUS volumes, and I have already adapted the landing page for this resource too:

- https://history.state.gov/open/frus-metadata.xml
- https://history.state.gov/beta/open/frus-metadata

Please adapt the code for both feeds from `/db/history/modules/open.xqm`. Attached here for convenience: [open.xqm.zip](https://github.com/eXistSolutions/hsg-shell/files/83069/open.xqm.zip)

**Comment by patczar** [comment]
I think it's mostly made.
Some doubts that I have regard:
- using data from bibliography collection; I hope this is what was expected,
- obtaining the actual application root URL; I wrote it in controller.xql and hope that I haven't broken anything.

**Comment by patczar** [comment]
After a few hours of learning and trying tei processing model (thanks in particular @wolfgangmm @tuurma and @line-o), I made also the translation of summaries into HTML.
Proposing as the final solution.
Maybe I close to notify on the status? Please open if you find any issue in my approach.

**Comment by joewiz** [comment]
Similar to #98, the Atom feeds are not adjusting to production server's URL.  The feed at https://history.state.gov/open/frus-latest.xml is returning:

```
<feed xmlns="http://www.w3.org/2005/Atom">
    <title>Foreign Relations of the United States: Latest Volumes</title>
    <subtitle>The 10 most recently published volumes in the Foreign Relations of the United States series, sorted by year of publication.</subtitle>
    <link href="https://history.state.gov:443/exist/apps/hsg-shell/open/frus-latest.xml" rel="self"/>
    <id>http://history.state.us/atom/frus-metadata-v1</id>
...
```

The `<link>` and all other URLs on the page are

    https://history.state.gov:443/exist/apps/hsg-shell/open/frus-latest.xml

but should be this on the production server:

    https://history.state.gov/open/frus-latest.xml

(Drop the port and `/exist/apps/hsg-shell`.)
