### ISSUE TITLE
Adapt ebooks OPDS API

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#98]
history.state.gov has an OPDS API exposing the FRUS ebooks catalog - see documentation at:

- https://history.state.gov/developer/catalog

I have already adapted the documentation for this section:

- http://localhost:8080/exist/apps/hsg-shell/developer
- http://localhost:8080/exist/apps/hsg-shell/developer/catalog

But the feed itself is not yet adapted. Please adapt it from `/db/history/modules/opds.xqm`, attached here: 
[opds.xqm.zip](https://github.com/eXistSolutions/hsg-shell/files/83078/opds.xqm.zip). Please test against the same queries and results in the documentation (from the `developer/catalog` page linked above).

**Comment by patczar** [comment]
I've adapted the old solution, which means that I
- changed the paths (used configuration variables as much as possible),
- referred to existing functions from frus-html and tags-html modules,
- wrote a URL-rewriting section in controller.xql.
But without deep understanding of the logic nuances, I haven't tried to refactor the code, which might be rational at this point... There is a little code duplication (between browse and search for instance) and the layout of modules is not ideally logical (some ebooks-related code exists in frus-html; maybe it could be extracted to an external one). I address those code style comments to @wolfgangmm , let him decide if we want to touch anything.

**Comment by patczar** [comment]
As far as I can see, there is only one volume conforming the ebook requirements (BTW aren't they too strict - we require .epub to be present), "China, 1973–1976".
My tests were very limited. "Something works" at first glance, in particular tag / subtags browsing, but I'd hold on with closing this issue until somebody who knows how it should really work test it.
Thanks.

**Comment by joewiz** [comment]
@patczar To add the full list of ebooks you need the S3 credentials, an issue described in #54. See the related discussion at https://trello.com/c/BleflNgu/48-api-keys. Once you have the s3 app set up correctly, you can grab the full list of ebook resources stored in S3 via http://localhost:8080/exist/apps/s3/cache-all.xq. As a workaround (avoiding the whole API key issue), you can fetch an older subset of available ebooks by calling http://localhost:8080/exist/apps/s3/load-cache-from-zip.xq. Once you have a larger set of volumes available, it would be great if you test your local OPDS endpoint using an OPDS-compliant ebook reader like ShuBook (iOS) or Bluefire or Alkido (Android; haven't used these on Android myself).

**Comment by joewiz** [comment]
Thanks for your work on this so far @patczar. I see a couple of issues:

- The API's main URL is returning non-well-formed XML. See http://localhost:8080/exist/apps/hsg-shell/api/v1/catalog:

```xml

<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
    <id>http://localhost:8080/exist/apps/hsg-shell/api/v1/catalog</id>
    <title>Office of the Historian Ebook Catalog</title>
    <updated>2016-03-16T09:37:50.554-04:00</updated>
    <author>
        <name>Office of the Historian</name>
        <uri>http://localhost:8080/exist/apps/hsg-shell/</uri>
    </author>
    <link type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="self" href="http://localhost:8080/exist/apps/hsg-shell/api/v1/catalog" title="Office of the Historian Ebook Catalog"/>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="start" href="http://localhost:8080/exist/apps/hsg-shell/api/v1/catalog" title="Foreign Relations of the United States"/>
    <link type="application/opensearchdescription+xml" rel="search" href="http://localhost:8080/exist/apps/hsg-shell/opensearch.xml" title="Search Office of the Historian ebooks"/>
    <entry>
        <title>All Volumes</title>
        <id>all</id>
        <updated>2016-03-16T09:37:50.554-04:00</updated>
        <summary type="text">All Foreign Relations of the United States series ebooks</summary>
        <link type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="subsection" href="http://localhost:8080/exist/apps/hsg-shell/api/v1/catalog/all" title="Foreign Relations of the United States Ebook Catalog"/>
    </entry>
   ...
</feed>
<a>frus1969-76v18</a>
```

As you can see, there is an atom `<feed>` element, followed by an `<a>` element. Please remove the `<a>` element. 

(Assuming you were outputting the `<a>` element for debugging purposes, let me suggest a good alternative: the `console:log` function. You can find more info on this at http://localhost:8080/exist/apps/monex/console.html.)

- On the hsg/beta site, the `<link @href>` and `<id>` URLs reference `localhost:8080/beta/exist/...` rather than the site's public URL. For example, see https://history.state.gov/beta/exist/apps/hsg-shell/api/v1/catalog. Compare to https://history.state.gov/api/v1/catalog. To establish whether the site is in beta vs. production vs. development, see https://github.com/eXistSolutions/hsg-shell/blob/master/modules/app.xqm#L62.

**Comment by joewiz** [comment]
(Update: I just corrected the hsg beta URL.)

**Comment by patczar** [comment]
I removed the unwanted <a>. Yes, it was for debugging, thanks for hint :)
The current status here is - I think - to wait for #54.

**Comment by joewiz** [comment]
As was the case with my Mar 16 report, the URLs generated by the ebook API on the production server are wrong:
```

<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
    <id>https://history.state.gov/exist/apps/hsg-shell/api/v1/catalog</id>
    <title>Office of the Historian Ebook Catalog</title>
    <updated>2016-04-28T18:28:38.683Z</updated>
    <author>
        <name>Office of the Historian</name>
        <uri>https://history.state.gov/exist/apps/hsg-shell/</uri>
    </author>
    <link type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="self" href="https://history.state.gov/exist/apps/hsg-shell/api/v1/catalog" title="Office of the Historian Ebook Catalog"/>
    <link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="start" href="https://history.state.gov/exist/apps/hsg-shell/api/v1/catalog" title="Foreign Relations of the United States"/>
    <link type="application/opensearchdescription+xml" rel="search" href="https://history.state.gov/exist/apps/hsg-shell/opensearch.xml" title="Search Office of the Historian ebooks"/>
    <entry>
        <title>All Volumes</title>
        <id>all</id>
        <updated>2016-04-28T18:28:38.683Z</updated>
        <summary type="text">All Foreign Relations of the United States series ebooks</summary>
        <link type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="subsection" href="https://history.state.gov/exist/apps/hsg-shell/api/v1/catalog/all" title="Foreign Relations of the United States Ebook Catalog"/>
    </entry>
    <entry>
        <title>Recently Published</title>
        <id>recent</id>
        <updated>2016-04-28T18:28:38.683Z</updated>
        <summary type="text">10 Most Recently Published Volumes</summary>
        <link type="application/atom+xml;profile=opds-catalog;kind=acquisition" rel="http://opds-spec.org/sort/new" href="https://history.state.gov/exist/apps/hsg-shell/api/v1/catalog/recent" title="10 Most Recently Published"/>
    </entry>
    <entry>
        <title>Browse By Keywords</title>
        <id>browse</id>
        <updated>2016-04-28T18:28:38.683Z</updated>
        <summary type="text">Browse By Keywords</summary>
        <link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" href="https://history.state.gov/exist/apps/hsg-shell/api/v1/catalog/browse" title="Browse By Keywords"/>
    </entry>
</feed>
```

All URLs showing up as:

    https://history.state.gov/exist/apps/hsg-shell/api/v1/

should instead be showing up as:

    https://history.state.gov/api/v1/

Of course, though, when viewed on a stock eXist installation, the URL should include the `exist/apps/hsg-shell/` bit. See how we handle `$app` elsewhere in hsg-shell.

**Comment by patczar** [comment]
The URLs should adapt to the request. When a client requests https://history.state.gov/api/v1/catalog , then the links should start with https://history.state.gov/api/v1/catalog (without the exist part). That is how it's written, using substring-before.  (At the moment I can see relative paths on production - still the old version?)
Anyway, I'll look at $app in other places, probably it is a better way to write it.
