### ISSUE TITLE
Adapt volume-ids service

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#99]
Our FRUS TEI schematron relies on the presence of a service on hsg for reporting the list of valid volume IDs:

- https://history.state.gov/services/volume-ids

Please adapt this from `/db/history/services/volume-ids.xq`, attached here: [volume-ids.xq.zip](https://github.com/eXistSolutions/hsg-shell/files/83097/volume-ids.xq.zip).

**Comment by patczar** [comment]
Done. Adapted your approach with reading the list of xml files.
I tried also with reading xml:id from the volumes, but at least one of the documents misses it (frus1917-72PubDip.xml) and it would probably be slower.
The list is available as http://localhost:8080/exist/apps/hsg-shell/modules/volume-ids.xql (for localhost). To remove the "modules/" and ".xql" parts, we can involve some URL-rewriting, but I'd have to consult Wolfgang about it.
